#pragma once
// AUTO-GENERATED by codegen/codegen.py — DO NOT EDIT
// Contains 271 CUDA Driver API function RPC declarations
//
// This file is included by both the client shim and the server.
// It defines the RPC message types (request/response structs) and
// the zpp::bits::rpc<> binding that maps function indices to handlers.

#include <zpp_bits.h>
#include <cstdint>
#include <string>

namespace cuda_gen {

// ── cuInit | barrier ──
struct InitRet {
    int32_t result;
};
InitRet init(uint32_t Flags);

// ── cuDriverGetVersion | barrier ──
struct DriverGetVersionRet {
    int32_t result;
    int32_t driverVersion;
};
DriverGetVersionRet driver_get_version();

// ── cuDeviceGetCount | barrier ──
struct DeviceGetCountRet {
    int32_t result;
    int32_t count;
};
DeviceGetCountRet device_get_count();

// ── cuDeviceGet | barrier ──
struct DeviceGetRet {
    int32_t result;
    int32_t device;
};
DeviceGetRet device_get(int32_t ordinal);

// ── cuDeviceGetName | barrier ──
struct DeviceGetNameRet {
    int32_t result;
    uint64_t name;
};
DeviceGetNameRet device_get_name(int32_t len, int32_t dev);

// ── cuDeviceTotalMem | barrier ──
struct DeviceTotalMemRet {
    int32_t result;
    uint64_t bytes;
};
DeviceTotalMemRet device_total_mem(int32_t dev);

// ── cuDeviceTotalMem_v2 | barrier ──
struct DeviceTotalMemV2Ret {
    int32_t result;
    uint64_t bytes;
};
DeviceTotalMemV2Ret device_total_mem_v2(int32_t dev);

// ── cuDeviceGetAttribute | barrier ──
struct DeviceGetAttributeRet {
    int32_t result;
    int32_t value;
};
DeviceGetAttributeRet device_get_attribute(uint32_t attrib, int32_t dev);

// ── cuDeviceGetMemPool | barrier ──
struct DeviceGetMemPoolRet {
    int32_t result;
    uint64_t pool;  // PRODUCES handle
};
DeviceGetMemPoolRet device_get_mem_pool(int32_t dev);

// ── cuDeviceSetMemPool | enqueued ──
struct DeviceSetMemPoolRet {
    int32_t result;
};
DeviceSetMemPoolRet device_set_mem_pool(int32_t dev, uint64_t pool);

// ── cuDeviceGetExecAffinitySupport | barrier ──
struct DeviceGetExecAffinitySupportRet {
    int32_t result;
    int32_t pi;
};
DeviceGetExecAffinitySupportRet device_get_exec_affinity_support(uint32_t flag, int32_t dev);

// ── cuDeviceGetCudaComputeCapability | barrier ──
struct DeviceGetCudaComputeCapabilityRet {
    int32_t result;
    int32_t major;
    int32_t minor;
};
DeviceGetCudaComputeCapabilityRet device_get_cuda_compute_capability(int32_t dev);

// ── cuDevicePrimaryCtxRetain | barrier ──
struct DevicePrimaryCtxRetainRet {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
DevicePrimaryCtxRetainRet device_primary_ctx_retain(int32_t dev);

// ── cuDevicePrimaryCtxRelease | enqueued ──
struct DevicePrimaryCtxReleaseRet {
    int32_t result;
};
DevicePrimaryCtxReleaseRet device_primary_ctx_release(int32_t dev);

// ── cuDevicePrimaryCtxRelease_v2 | enqueued ──
struct DevicePrimaryCtxReleaseV2Ret {
    int32_t result;
};
DevicePrimaryCtxReleaseV2Ret device_primary_ctx_release_v2(int32_t dev);

// ── cuDevicePrimaryCtxSetFlags | enqueued ──
struct DevicePrimaryCtxSetFlagsRet {
    int32_t result;
};
DevicePrimaryCtxSetFlagsRet device_primary_ctx_set_flags(int32_t dev, uint32_t flags);

// ── cuDevicePrimaryCtxSetFlags_v2 | enqueued ──
struct DevicePrimaryCtxSetFlagsV2Ret {
    int32_t result;
};
DevicePrimaryCtxSetFlagsV2Ret device_primary_ctx_set_flags_v2(int32_t dev, uint32_t flags);

// ── cuDevicePrimaryCtxGetState | barrier ──
struct DevicePrimaryCtxGetStateRet {
    int32_t result;
    uint32_t flags;
    int32_t active;
};
DevicePrimaryCtxGetStateRet device_primary_ctx_get_state(int32_t dev);

// ── cuCtxCreate | barrier ──
struct CtxCreateRet {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
CtxCreateRet ctx_create(uint32_t flags, int32_t dev);

// ── cuCtxCreate_v2 | barrier ──
struct CtxCreateV2Ret {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
CtxCreateV2Ret ctx_create_v2(uint32_t flags, int32_t dev);

// ── cuCtxDestroy | enqueued ──
struct CtxDestroyRet {
    int32_t result;
};
CtxDestroyRet ctx_destroy(uint64_t ctx);

// ── cuCtxDestroy_v2 | enqueued ──
struct CtxDestroyV2Ret {
    int32_t result;
};
CtxDestroyV2Ret ctx_destroy_v2(uint64_t ctx);

// ── cuCtxSetCurrent | barrier ──
struct CtxSetCurrentRet {
    int32_t result;
};
CtxSetCurrentRet ctx_set_current(uint64_t ctx);

// ── cuCtxGetCurrent | barrier ──
struct CtxGetCurrentRet {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
CtxGetCurrentRet ctx_get_current();

// ── cuCtxPushCurrent | barrier ──
struct CtxPushCurrentRet {
    int32_t result;
};
CtxPushCurrentRet ctx_push_current(uint64_t ctx);

// ── cuCtxPushCurrent_v2 | barrier ──
struct CtxPushCurrentV2Ret {
    int32_t result;
};
CtxPushCurrentV2Ret ctx_push_current_v2(uint64_t ctx);

// ── cuCtxPopCurrent | barrier ──
struct CtxPopCurrentRet {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
CtxPopCurrentRet ctx_pop_current();

// ── cuCtxPopCurrent_v2 | barrier ──
struct CtxPopCurrentV2Ret {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
CtxPopCurrentV2Ret ctx_pop_current_v2();

// ── cuCtxSetFlags | enqueued ──
struct CtxSetFlagsRet {
    int32_t result;
};
CtxSetFlagsRet ctx_set_flags(uint32_t flags);

// ── cuCtxSetFlags_v2 | enqueued ──
struct CtxSetFlagsV2Ret {
    int32_t result;
};
CtxSetFlagsV2Ret ctx_set_flags_v2(uint32_t flags);

// ── cuCtxSynchronize | barrier ──
struct CtxSynchronizeRet {
    int32_t result;
};
CtxSynchronizeRet ctx_synchronize();

// ── cuCtxGetDevice | barrier ──
struct CtxGetDeviceRet {
    int32_t result;
    int32_t device;
};
CtxGetDeviceRet ctx_get_device();

// ── cuCtxGetFlags | barrier ──
struct CtxGetFlagsRet {
    int32_t result;
    uint32_t flags;
};
CtxGetFlagsRet ctx_get_flags();

// ── cuCtxGetStreamPriorityRange | barrier ──
struct CtxGetStreamPriorityRangeRet {
    int32_t result;
    int32_t leastPriority;
    int32_t greatestPriority;
};
CtxGetStreamPriorityRangeRet ctx_get_stream_priority_range();

// ── cuCtxGetCacheConfig | barrier ──
struct CtxGetCacheConfigRet {
    int32_t result;
    uint32_t config;
};
CtxGetCacheConfigRet ctx_get_cache_config();

// ── cuCtxSetCacheConfig | enqueued ──
struct CtxSetCacheConfigRet {
    int32_t result;
};
CtxSetCacheConfigRet ctx_set_cache_config(uint32_t config);

// ── cuCtxGetSharedMemConfig | barrier ──
struct CtxGetSharedMemConfigRet {
    int32_t result;
    uint32_t pConfig;
};
CtxGetSharedMemConfigRet ctx_get_shared_mem_config();

// ── cuCtxSetSharedMemConfig | enqueued ──
struct CtxSetSharedMemConfigRet {
    int32_t result;
};
CtxSetSharedMemConfigRet ctx_set_shared_mem_config(uint32_t config);

// ── cuCtxGetApiVersion | barrier ──
struct CtxGetApiVersionRet {
    int32_t result;
    uint32_t apiVersion;
};
CtxGetApiVersionRet ctx_get_api_version(uint64_t ctx);

// ── cuCtxGetLimit | barrier ──
struct CtxGetLimitRet {
    int32_t result;
    uint64_t pvalue;
};
CtxGetLimitRet ctx_get_limit(uint32_t limit);

// ── cuCtxSetLimit | enqueued ──
struct CtxSetLimitRet {
    int32_t result;
};
CtxSetLimitRet ctx_set_limit(uint32_t limit, uint64_t value);

// ── cuCtxEnablePeerAccess | enqueued ──
struct CtxEnablePeerAccessRet {
    int32_t result;
};
CtxEnablePeerAccessRet ctx_enable_peer_access(uint64_t peerContext, uint32_t Flags);

// ── cuCtxDisablePeerAccess | enqueued ──
struct CtxDisablePeerAccessRet {
    int32_t result;
};
CtxDisablePeerAccessRet ctx_disable_peer_access(uint64_t peerContext);

// ── cuMemAlloc | barrier ──
struct MemAllocRet {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocRet mem_alloc(uint64_t bytesize);

// ── cuMemAlloc_v2 | barrier ──
struct MemAllocV2Ret {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocV2Ret mem_alloc_v2(uint64_t bytesize);

// ── cuMemAllocManaged | barrier ──
struct MemAllocManagedRet {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocManagedRet mem_alloc_managed(uint64_t bytesize, uint32_t flags);

// ── cuMemAllocManaged_v2 | barrier ──
struct MemAllocManagedV2Ret {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocManagedV2Ret mem_alloc_managed_v2(uint64_t bytesize, uint32_t flags);

// ── cuMemFree | enqueued ──
struct MemFreeRet {
    int32_t result;
};
MemFreeRet mem_free(uint64_t dptr);

// ── cuMemFree_v2 | enqueued ──
struct MemFreeV2Ret {
    int32_t result;
};
MemFreeV2Ret mem_free_v2(uint64_t dptr);

// ── cuMemFreeHost | enqueued ──
struct MemFreeHostRet {
    int32_t result;
};
MemFreeHostRet mem_free_host(uint64_t p);

// ── cuMemHostAlloc | barrier ──
struct MemHostAllocRet {
    int32_t result;
    uint64_t pp;  // PRODUCES handle
};
MemHostAllocRet mem_host_alloc(uint64_t bytesize, uint32_t Flags);

// ── cuMemHostRegister | enqueued ──
struct MemHostRegisterRet {
    int32_t result;
};
MemHostRegisterRet mem_host_register(uint64_t p, uint64_t bytesize, uint32_t Flags);

// ── cuMemHostRegister_v2 | enqueued ──
struct MemHostRegisterV2Ret {
    int32_t result;
};
MemHostRegisterV2Ret mem_host_register_v2(uint64_t p, uint64_t bytesize, uint32_t Flags);

// ── cuMemHostUnregister | enqueued ──
struct MemHostUnregisterRet {
    int32_t result;
};
MemHostUnregisterRet mem_host_unregister(uint64_t p);

// ── cuMemHostGetDevicePointer | barrier ──
struct MemHostGetDevicePointerRet {
    int32_t result;
    uint64_t pdptr;  // PRODUCES devptr
};
MemHostGetDevicePointerRet mem_host_get_device_pointer(uint64_t p, uint32_t Flags);

// ── cuMemHostGetDevicePointer_v2 | barrier ──
struct MemHostGetDevicePointerV2Ret {
    int32_t result;
    uint64_t pdptr;  // PRODUCES devptr
};
MemHostGetDevicePointerV2Ret mem_host_get_device_pointer_v2(uint64_t p, uint32_t Flags);

// ── cuMemHostGetFlags | barrier ──
struct MemHostGetFlagsRet {
    int32_t result;
    uint32_t pFlags;
};
MemHostGetFlagsRet mem_host_get_flags(uint64_t p);

// ── cuMemGetInfo | barrier ──
struct MemGetInfoRet {
    int32_t result;
    uint64_t free;
    uint64_t total;
};
MemGetInfoRet mem_get_info();

// ── cuMemGetInfo_v2 | barrier ──
struct MemGetInfoV2Ret {
    int32_t result;
    uint64_t free;
    uint64_t total;
};
MemGetInfoV2Ret mem_get_info_v2();

// ── cuMemAllocPitch | barrier ──
struct MemAllocPitchRet {
    int32_t result;
    uint64_t pPitch;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocPitchRet mem_alloc_pitch(uint64_t WidthInBytes, uint64_t Height, uint32_t ElementSizeBytes);

// ── cuMemAllocPitch_v2 | barrier ──
struct MemAllocPitchV2Ret {
    int32_t result;
    uint64_t pPitch;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocPitchV2Ret mem_alloc_pitch_v2(uint64_t WidthInBytes, uint64_t Height, uint32_t ElementSizeBytes);

// ── cuMemcpyHtoD | enqueued ──
struct MemcpyHtoDRet {
    int32_t result;
};
MemcpyHtoDRet memcpy_hto_d(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount);

// ── cuMemcpyHtoD_v2 | enqueued ──
struct MemcpyHtoDV2Ret {
    int32_t result;
};
MemcpyHtoDV2Ret memcpy_hto_d_v2(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount);

// ── cuMemcpyDtoH | readback ──
struct MemcpyDtoHRet {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHRet memcpy_dto_h(uint64_t srcDevice, uint64_t ByteCount);

// ── cuMemcpyDtoH_v2 | readback ──
struct MemcpyDtoHV2Ret {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHV2Ret memcpy_dto_h_v2(uint64_t srcDevice, uint64_t ByteCount);

// ── cuMemcpyDtoD | enqueued ──
struct MemcpyDtoDRet {
    int32_t result;
};
MemcpyDtoDRet memcpy_dto_d(uint64_t dstDevice, uint64_t srcDevice, uint64_t ByteCount);

// ── cuMemcpyDtoD_v2 | enqueued ──
struct MemcpyDtoDV2Ret {
    int32_t result;
};
MemcpyDtoDV2Ret memcpy_dto_d_v2(uint64_t dstDevice, uint64_t srcDevice, uint64_t ByteCount);

// ── cuMemcpyHtoDAsync | enqueued ──
struct MemcpyHtoDAsyncRet {
    int32_t result;
};
MemcpyHtoDAsyncRet memcpy_hto_d_async(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyHtoDAsync_v2 | enqueued ──
struct MemcpyHtoDAsyncV2Ret {
    int32_t result;
};
MemcpyHtoDAsyncV2Ret memcpy_hto_d_async_v2(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyDtoHAsync | readback ──
struct MemcpyDtoHAsyncRet {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHAsyncRet memcpy_dto_h_async(uint64_t srcDevice, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyDtoHAsync_v2 | readback ──
struct MemcpyDtoHAsyncV2Ret {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHAsyncV2Ret memcpy_dto_h_async_v2(uint64_t srcDevice, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyDtoDAsync | enqueued ──
struct MemcpyDtoDAsyncRet {
    int32_t result;
};
MemcpyDtoDAsyncRet memcpy_dto_d_async(uint64_t dstDevice, uint64_t srcDevice, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyDtoDAsync_v2 | enqueued ──
struct MemcpyDtoDAsyncV2Ret {
    int32_t result;
};
MemcpyDtoDAsyncV2Ret memcpy_dto_d_async_v2(uint64_t dstDevice, uint64_t srcDevice, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpy | enqueued ──
struct MemcpyRet {
    int32_t result;
};
MemcpyRet memcpy(uint64_t dst, uint64_t src, uint64_t ByteCount);

// ── cuMemcpy_v2 | enqueued ──
struct MemcpyV2Ret {
    int32_t result;
};
MemcpyV2Ret memcpy_v2(uint64_t dst, uint64_t src, uint64_t ByteCount);

// ── cuMemcpyAsync | enqueued ──
struct MemcpyAsyncRet {
    int32_t result;
};
MemcpyAsyncRet memcpy_async(uint64_t dst, uint64_t src, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyPeer | enqueued ──
struct MemcpyPeerRet {
    int32_t result;
};
MemcpyPeerRet memcpy_peer(uint64_t dstDevice, uint64_t dstContext, uint64_t srcDevice, uint64_t srcContext, uint64_t ByteCount);

// ── cuMemcpyPeer_v2 | enqueued ──
struct MemcpyPeerV2Ret {
    int32_t result;
};
MemcpyPeerV2Ret memcpy_peer_v2(uint64_t dstDevice, uint64_t dstContext, uint64_t srcDevice, uint64_t srcContext, uint64_t ByteCount);

// ── cuMemcpyPeerAsync | enqueued ──
struct MemcpyPeerAsyncRet {
    int32_t result;
};
MemcpyPeerAsyncRet memcpy_peer_async(uint64_t dstDevice, uint64_t dstContext, uint64_t srcDevice, uint64_t srcContext, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyPeerAsync_v2 | enqueued ──
struct MemcpyPeerAsyncV2Ret {
    int32_t result;
};
MemcpyPeerAsyncV2Ret memcpy_peer_async_v2(uint64_t dstDevice, uint64_t dstContext, uint64_t srcDevice, uint64_t srcContext, uint64_t ByteCount, uint64_t hStream);

// ── cuMemsetD8 | enqueued ──
struct MemsetD8Ret {
    int32_t result;
};
MemsetD8Ret memset_d8(uint64_t dstDevice, uint32_t uc, uint64_t N);

// ── cuMemsetD8_v2 | enqueued ──
struct MemsetD8V2Ret {
    int32_t result;
};
MemsetD8V2Ret memset_d8_v2(uint64_t dstDevice, uint32_t uc, uint64_t N);

// ── cuMemsetD16 | enqueued ──
struct MemsetD16Ret {
    int32_t result;
};
MemsetD16Ret memset_d16(uint64_t dstDevice, uint32_t us, uint64_t N);

// ── cuMemsetD16_v2 | enqueued ──
struct MemsetD16V2Ret {
    int32_t result;
};
MemsetD16V2Ret memset_d16_v2(uint64_t dstDevice, uint32_t us, uint64_t N);

// ── cuMemsetD32 | enqueued ──
struct MemsetD32Ret {
    int32_t result;
};
MemsetD32Ret memset_d32(uint64_t dstDevice, uint32_t ui, uint64_t N);

// ── cuMemsetD32_v2 | enqueued ──
struct MemsetD32V2Ret {
    int32_t result;
};
MemsetD32V2Ret memset_d32_v2(uint64_t dstDevice, uint32_t ui, uint64_t N);

// ── cuMemsetD2D8 | enqueued ──
struct MemsetD2D8Ret {
    int32_t result;
};
MemsetD2D8Ret memset_d2_d8(uint64_t dstDevice, uint64_t dstPitch, uint32_t uc, uint64_t Width, uint64_t Height);

// ── cuMemsetD2D8_v2 | enqueued ──
struct MemsetD2D8V2Ret {
    int32_t result;
};
MemsetD2D8V2Ret memset_d2_d8_v2(uint64_t dstDevice, uint64_t dstPitch, uint32_t uc, uint64_t Width, uint64_t Height);

// ── cuMemsetD2D16 | enqueued ──
struct MemsetD2D16Ret {
    int32_t result;
};
MemsetD2D16Ret memset_d2_d16(uint64_t dstDevice, uint64_t dstPitch, uint32_t us, uint64_t Width, uint64_t Height);

// ── cuMemsetD2D16_v2 | enqueued ──
struct MemsetD2D16V2Ret {
    int32_t result;
};
MemsetD2D16V2Ret memset_d2_d16_v2(uint64_t dstDevice, uint64_t dstPitch, uint32_t us, uint64_t Width, uint64_t Height);

// ── cuMemsetD2D32 | enqueued ──
struct MemsetD2D32Ret {
    int32_t result;
};
MemsetD2D32Ret memset_d2_d32(uint64_t dstDevice, uint64_t dstPitch, uint32_t ui, uint64_t Width, uint64_t Height);

// ── cuMemsetD2D32_v2 | enqueued ──
struct MemsetD2D32V2Ret {
    int32_t result;
};
MemsetD2D32V2Ret memset_d2_d32_v2(uint64_t dstDevice, uint64_t dstPitch, uint32_t ui, uint64_t Width, uint64_t Height);

// ── cuMemsetD8Async | enqueued ──
struct MemsetD8AsyncRet {
    int32_t result;
};
MemsetD8AsyncRet memset_d8_async(uint64_t dstDevice, uint32_t uc, uint64_t N, uint64_t hStream);

// ── cuMemsetD16Async | enqueued ──
struct MemsetD16AsyncRet {
    int32_t result;
};
MemsetD16AsyncRet memset_d16_async(uint64_t dstDevice, uint32_t us, uint64_t N, uint64_t hStream);

// ── cuMemsetD32Async | enqueued ──
struct MemsetD32AsyncRet {
    int32_t result;
};
MemsetD32AsyncRet memset_d32_async(uint64_t dstDevice, uint32_t ui, uint64_t N, uint64_t hStream);

// ── cuMemsetD2D8Async | enqueued ──
struct MemsetD2D8AsyncRet {
    int32_t result;
};
MemsetD2D8AsyncRet memset_d2_d8_async(uint64_t dstDevice, uint64_t dstPitch, uint32_t uc, uint64_t Width, uint64_t Height, uint64_t hStream);

// ── cuMemsetD2D16Async | enqueued ──
struct MemsetD2D16AsyncRet {
    int32_t result;
};
MemsetD2D16AsyncRet memset_d2_d16_async(uint64_t dstDevice, uint64_t dstPitch, uint32_t us, uint64_t Width, uint64_t Height, uint64_t hStream);

// ── cuMemsetD2D32Async | enqueued ──
struct MemsetD2D32AsyncRet {
    int32_t result;
};
MemsetD2D32AsyncRet memset_d2_d32_async(uint64_t dstDevice, uint64_t dstPitch, uint32_t ui, uint64_t Width, uint64_t Height, uint64_t hStream);

// ── cuMemAddressReserve | barrier ──
struct MemAddressReserveRet {
    int32_t result;
    uint64_t ptr;  // PRODUCES devptr
};
MemAddressReserveRet mem_address_reserve(uint64_t size, uint64_t alignment, uint64_t addr, uint64_t flags);

// ── cuMemAddressFree | enqueued ──
struct MemAddressFreeRet {
    int32_t result;
};
MemAddressFreeRet mem_address_free(uint64_t ptr, uint64_t size);

// ── cuMemCreate | barrier ──
struct MemCreateRet {
    int32_t result;
    uint64_t handle;  // PRODUCES handle
};
MemCreateRet mem_create(uint64_t size, uint64_t desc, uint64_t flags);

// ── cuMemRelease | enqueued ──
struct MemReleaseRet {
    int32_t result;
};
MemReleaseRet mem_release(uint64_t handle);

// ── cuMemMap | enqueued ──
struct MemMapRet {
    int32_t result;
};
MemMapRet mem_map(uint64_t ptr, uint64_t size, uint64_t offset, uint64_t handle);

// ── cuMemUnmap | enqueued ──
struct MemUnmapRet {
    int32_t result;
};
MemUnmapRet mem_unmap(uint64_t ptr, uint64_t size);

// ── cuMemSetAccess | enqueued ──
struct MemSetAccessRet {
    int32_t result;
};
MemSetAccessRet mem_set_access(uint64_t ptr, uint64_t size, uint64_t desc, uint64_t count);

// ── cuMemGetAccess | barrier ──
struct MemGetAccessRet {
    int32_t result;
    uint64_t flags;
};
MemGetAccessRet mem_get_access(uint64_t location, uint64_t ptr);

// ── cuMemGetAllocationGranularity | barrier ──
struct MemGetAllocationGranularityRet {
    int32_t result;
    uint64_t granularity;
};
MemGetAllocationGranularityRet mem_get_allocation_granularity(uint64_t prop, uint64_t flags);

// ── cuMemRetainAllocationHandle | barrier ──
struct MemRetainAllocationHandleRet {
    int32_t result;
    uint64_t handle;  // PRODUCES handle
};
MemRetainAllocationHandleRet mem_retain_allocation_handle(uint64_t addr);

// ── cuModuleLoad | barrier ──
struct ModuleLoadRet {
    int32_t result;
    uint64_t module;  // PRODUCES handle
};
ModuleLoadRet module_load(std::string fname);

// ── cuModuleLoadData | barrier ──
struct ModuleLoadDataRet {
    int32_t result;
    uint64_t module;  // PRODUCES handle
};
ModuleLoadDataRet module_load_data(uint64_t image);

// ── cuModuleLoadDataEx | barrier ──
struct ModuleLoadDataExRet {
    int32_t result;
    uint64_t module;  // PRODUCES handle
};
ModuleLoadDataExRet module_load_data_ex(uint64_t image, uint32_t numOptions, uint64_t options, uint64_t optionValues);

// ── cuModuleLoadFatBinary | barrier ──
struct ModuleLoadFatBinaryRet {
    int32_t result;
    uint64_t module;  // PRODUCES handle
};
ModuleLoadFatBinaryRet module_load_fat_binary(uint64_t fatCubin);

// ── cuModuleUnload | enqueued ──
struct ModuleUnloadRet {
    int32_t result;
};
ModuleUnloadRet module_unload(uint64_t hmod);

// ── cuModuleGetFunction | barrier ──
struct ModuleGetFunctionRet {
    int32_t result;
    uint64_t hfunc;  // PRODUCES handle
};
ModuleGetFunctionRet module_get_function(uint64_t hmod, std::string name);

// ── cuModuleGetGlobal | barrier ──
struct ModuleGetGlobalRet {
    int32_t result;
    uint64_t bytes;
    uint64_t dptr;  // PRODUCES devptr
};
ModuleGetGlobalRet module_get_global(uint64_t hmod, std::string name);

// ── cuModuleGetGlobal_v2 | barrier ──
struct ModuleGetGlobalV2Ret {
    int32_t result;
    uint64_t bytes;
    uint64_t dptr;  // PRODUCES devptr
};
ModuleGetGlobalV2Ret module_get_global_v2(uint64_t hmod, std::string name);

// ── cuModuleGetTexRef | barrier ──
struct ModuleGetTexRefRet {
    int32_t result;
    uint64_t pTexRef;  // PRODUCES handle
};
ModuleGetTexRefRet module_get_tex_ref(uint64_t hmod, std::string name);

// ── cuModuleGetSurfRef | barrier ──
struct ModuleGetSurfRefRet {
    int32_t result;
    uint64_t pSurfRef;  // PRODUCES handle
};
ModuleGetSurfRefRet module_get_surf_ref(uint64_t hmod, std::string name);

// ── cuLaunchKernel | enqueued ──
struct LaunchKernelRet {
    int32_t result;
};
LaunchKernelRet launch_kernel(uint64_t f, uint32_t gridDimX, uint32_t gridDimY, uint32_t gridDimZ, uint32_t blockDimX, uint32_t blockDimY, uint32_t blockDimZ, uint32_t sharedMemBytes, uint64_t hStream, uint64_t kernelParams, uint64_t extra);

// ── cuLaunchCooperativeKernel | enqueued ──
struct LaunchCooperativeKernelRet {
    int32_t result;
};
LaunchCooperativeKernelRet launch_cooperative_kernel(uint64_t f, uint32_t gridDimX, uint32_t gridDimY, uint32_t gridDimZ, uint32_t blockDimX, uint32_t blockDimY, uint32_t blockDimZ, uint32_t sharedMemBytes, uint64_t hStream, uint64_t kernelParams);

// ── cuLaunchHostFunc | enqueued ──
struct LaunchHostFuncRet {
    int32_t result;
};
LaunchHostFuncRet launch_host_func(uint64_t hStream, uint64_t fn, uint64_t userData);

// ── cuGetProcAddress | barrier ──
struct GetProcAddressRet {
    int32_t result;
    uint64_t pfn;
};
GetProcAddressRet get_proc_address(std::string symbol, int32_t cudaVersion, uint64_t flags);

// ── cuGetProcAddress_v2 | barrier ──
struct GetProcAddressV2Ret {
    int32_t result;
    uint64_t pfn;
    uint64_t symbolStatus;
};
GetProcAddressV2Ret get_proc_address_v2(std::string symbol, int32_t cudaVersion, uint64_t flags);

// ── cuStreamCreate | barrier ──
struct StreamCreateRet {
    int32_t result;
    uint64_t phStream;  // PRODUCES handle
};
StreamCreateRet stream_create(uint32_t Flags);

// ── cuStreamCreateWithPriority | barrier ──
struct StreamCreateWithPriorityRet {
    int32_t result;
    uint64_t phStream;  // PRODUCES handle
};
StreamCreateWithPriorityRet stream_create_with_priority(uint32_t flags, int32_t priority);

// ── cuStreamDestroy | enqueued ──
struct StreamDestroyRet {
    int32_t result;
};
StreamDestroyRet stream_destroy(uint64_t hStream);

// ── cuStreamDestroy_v2 | enqueued ──
struct StreamDestroyV2Ret {
    int32_t result;
};
StreamDestroyV2Ret stream_destroy_v2(uint64_t hStream);

// ── cuStreamSynchronize | barrier ──
struct StreamSynchronizeRet {
    int32_t result;
};
StreamSynchronizeRet stream_synchronize(uint64_t hStream);

// ── cuStreamGetPriority | barrier ──
struct StreamGetPriorityRet {
    int32_t result;
    int32_t priority;
};
StreamGetPriorityRet stream_get_priority(uint64_t hStream);

// ── cuStreamGetFlags | barrier ──
struct StreamGetFlagsRet {
    int32_t result;
    uint32_t flags;
};
StreamGetFlagsRet stream_get_flags(uint64_t hStream);

// ── cuStreamGetCtx | barrier ──
struct StreamGetCtxRet {
    int32_t result;
    uint64_t pctx;  // PRODUCES handle
};
StreamGetCtxRet stream_get_ctx(uint64_t hStream);

// ── cuStreamWaitEvent | enqueued ──
struct StreamWaitEventRet {
    int32_t result;
};
StreamWaitEventRet stream_wait_event(uint64_t hStream, uint64_t hEvent, uint32_t Flags);

// ── cuStreamWaitEvent_ptsz | enqueued ──
struct StreamWaitEventPtszRet {
    int32_t result;
};
StreamWaitEventPtszRet stream_wait_event_ptsz(uint64_t hStream, uint64_t hEvent, uint32_t Flags);

// ── cuStreamAddCallback | enqueued ──
struct StreamAddCallbackRet {
    int32_t result;
};
StreamAddCallbackRet stream_add_callback(uint64_t hStream, uint64_t callback, uint64_t userData, uint32_t flags);

// ── cuStreamAddCallback_ptsz | enqueued ──
struct StreamAddCallbackPtszRet {
    int32_t result;
};
StreamAddCallbackPtszRet stream_add_callback_ptsz(uint64_t hStream, uint64_t callback, uint64_t userData, uint32_t flags);

// ── cuStreamBeginCapture | enqueued ──
struct StreamBeginCaptureRet {
    int32_t result;
};
StreamBeginCaptureRet stream_begin_capture(uint64_t hStream, uint32_t mode);

// ── cuStreamBeginCapture_ptsz | enqueued ──
struct StreamBeginCapturePtszRet {
    int32_t result;
};
StreamBeginCapturePtszRet stream_begin_capture_ptsz(uint64_t hStream, uint32_t mode);

// ── cuStreamEndCapture | barrier ──
struct StreamEndCaptureRet {
    int32_t result;
    uint64_t phGraph;  // PRODUCES handle
};
StreamEndCaptureRet stream_end_capture(uint64_t hStream);

// ── cuStreamEndCapture_ptsz | barrier ──
struct StreamEndCapturePtszRet {
    int32_t result;
    uint64_t phGraph;  // PRODUCES handle
};
StreamEndCapturePtszRet stream_end_capture_ptsz(uint64_t hStream);

// ── cuStreamIsCapturing | barrier ──
struct StreamIsCapturingRet {
    int32_t result;
    uint32_t pCaptureStatus;
};
StreamIsCapturingRet stream_is_capturing(uint64_t hStream);

// ── cuStreamAttachMemAsync | enqueued ──
struct StreamAttachMemAsyncRet {
    int32_t result;
};
StreamAttachMemAsyncRet stream_attach_mem_async(uint64_t hStream, uint64_t dptr, uint64_t length, uint32_t flags);

// ── cuStreamAttachMemAsync_ptsz | enqueued ──
struct StreamAttachMemAsyncPtszRet {
    int32_t result;
};
StreamAttachMemAsyncPtszRet stream_attach_mem_async_ptsz(uint64_t hStream, uint64_t dptr, uint64_t length, uint32_t flags);

// ── cuStreamQuery | barrier ──
struct StreamQueryRet {
    int32_t result;
};
StreamQueryRet stream_query(uint64_t hStream);

// ── cuStreamQuery_ptsz | barrier ──
struct StreamQueryPtszRet {
    int32_t result;
};
StreamQueryPtszRet stream_query_ptsz(uint64_t hStream);

// ── cuEventCreate | barrier ──
struct EventCreateRet {
    int32_t result;
    uint64_t phEvent;  // PRODUCES handle
};
EventCreateRet event_create(uint32_t Flags);

// ── cuEventRecord | enqueued ──
struct EventRecordRet {
    int32_t result;
};
EventRecordRet event_record(uint64_t hEvent, uint64_t hStream);

// ── cuEventRecord_ptsz | enqueued ──
struct EventRecordPtszRet {
    int32_t result;
};
EventRecordPtszRet event_record_ptsz(uint64_t hEvent, uint64_t hStream);

// ── cuEventRecordWithFlags | enqueued ──
struct EventRecordWithFlagsRet {
    int32_t result;
};
EventRecordWithFlagsRet event_record_with_flags(uint64_t hEvent, uint32_t flags, uint64_t hStream);

// ── cuEventRecordWithFlags_ptsz | enqueued ──
struct EventRecordWithFlagsPtszRet {
    int32_t result;
};
EventRecordWithFlagsPtszRet event_record_with_flags_ptsz(uint64_t hEvent, uint32_t flags, uint64_t hStream);

// ── cuEventDestroy | enqueued ──
struct EventDestroyRet {
    int32_t result;
};
EventDestroyRet event_destroy(uint64_t hEvent);

// ── cuEventDestroy_v2 | enqueued ──
struct EventDestroyV2Ret {
    int32_t result;
};
EventDestroyV2Ret event_destroy_v2(uint64_t hEvent);

// ── cuEventSynchronize | barrier ──
struct EventSynchronizeRet {
    int32_t result;
};
EventSynchronizeRet event_synchronize(uint64_t hEvent);

// ── cuEventElapsedTime | barrier ──
struct EventElapsedTimeRet {
    int32_t result;
    float pMilliseconds;
};
EventElapsedTimeRet event_elapsed_time(uint64_t hStart, uint64_t hEnd);

// ── cuEventQuery | barrier ──
struct EventQueryRet {
    int32_t result;
};
EventQueryRet event_query(uint64_t hEvent);

// ── cuOccupancyMaxActiveBlocksPerMultiprocessor | barrier ──
struct OccupancyMaxActiveBlocksPerMultiprocessorRet {
    int32_t result;
    int32_t numBlocks;
};
OccupancyMaxActiveBlocksPerMultiprocessorRet occupancy_max_active_blocks_per_multiprocessor(uint64_t func, int32_t blockSize, uint64_t dynamicSMemSize);

// ── cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags | barrier ──
struct OccupancyMaxActiveBlocksPerMultiprocessorWithFlagsRet {
    int32_t result;
    int32_t numBlocks;
};
OccupancyMaxActiveBlocksPerMultiprocessorWithFlagsRet occupancy_max_active_blocks_per_multiprocessor_with_flags(uint64_t func, int32_t blockSize, uint64_t dynamicSMemSize, uint32_t flags);

// ── cuOccupancyMaxPotentialBlockSize | barrier ──
struct OccupancyMaxPotentialBlockSizeRet {
    int32_t result;
    int32_t minGridSize;
    int32_t blockSize;
};
OccupancyMaxPotentialBlockSizeRet occupancy_max_potential_block_size(uint64_t func, uint64_t block2Shmem, int32_t blockSizeLimit);

// ── cuOccupancyMaxPotentialBlockSizeWithFlags | barrier ──
struct OccupancyMaxPotentialBlockSizeWithFlagsRet {
    int32_t result;
    int32_t minGridSize;
    int32_t blockSize;
};
OccupancyMaxPotentialBlockSizeWithFlagsRet occupancy_max_potential_block_size_with_flags(uint64_t func, uint64_t block2Shmem, int32_t blockSizeLimit, uint32_t flags);

// ── cuOccupancyAvailableDynamicSMemPerBlock | barrier ──
struct OccupancyAvailableDynamicSMemPerBlockRet {
    int32_t result;
    uint64_t dynamicSmemSize;
};
OccupancyAvailableDynamicSMemPerBlockRet occupancy_available_dynamic_s_mem_per_block(uint64_t func, int32_t numBlocks, int32_t blockSize);

// ── cuTexRefSetArray | enqueued ──
struct TexRefSetArrayRet {
    int32_t result;
};
TexRefSetArrayRet tex_ref_set_array(uint64_t hTexRef, uint64_t hArray, uint32_t Flags);

// ── cuTexRefSetAddress | barrier ──
struct TexRefSetAddressRet {
    int32_t result;
    uint64_t ByteOffset;
};
TexRefSetAddressRet tex_ref_set_address(uint64_t hTexRef, uint64_t dptr, uint64_t bytes);

// ── cuTexRefSetAddress_v2 | barrier ──
struct TexRefSetAddressV2Ret {
    int32_t result;
    uint64_t ByteOffset;
};
TexRefSetAddressV2Ret tex_ref_set_address_v2(uint64_t hTexRef, uint64_t dptr, uint64_t bytes);

// ── cuTexRefSetFormat | enqueued ──
struct TexRefSetFormatRet {
    int32_t result;
};
TexRefSetFormatRet tex_ref_set_format(uint64_t hTexRef, uint32_t fmt, int32_t NumPackedComponents);

// ── cuTexRefSetAddressMode | enqueued ──
struct TexRefSetAddressModeRet {
    int32_t result;
};
TexRefSetAddressModeRet tex_ref_set_address_mode(uint64_t hTexRef, int32_t dim, uint32_t am);

// ── cuTexRefSetFilterMode | enqueued ──
struct TexRefSetFilterModeRet {
    int32_t result;
};
TexRefSetFilterModeRet tex_ref_set_filter_mode(uint64_t hTexRef, uint32_t fm);

// ── cuTexRefSetMipmapFilterMode | enqueued ──
struct TexRefSetMipmapFilterModeRet {
    int32_t result;
};
TexRefSetMipmapFilterModeRet tex_ref_set_mipmap_filter_mode(uint64_t hTexRef, uint32_t fm);

// ── cuTexRefSetMipmapLevelBias | enqueued ──
struct TexRefSetMipmapLevelBiasRet {
    int32_t result;
};
TexRefSetMipmapLevelBiasRet tex_ref_set_mipmap_level_bias(uint64_t hTexRef, float bias);

// ── cuTexRefSetMipmapLevelClamp | enqueued ──
struct TexRefSetMipmapLevelClampRet {
    int32_t result;
};
TexRefSetMipmapLevelClampRet tex_ref_set_mipmap_level_clamp(uint64_t hTexRef, float minMipmapLevelClamp, float maxMipmapLevelClamp);

// ── cuTexRefSetMaxAnisotropy | enqueued ──
struct TexRefSetMaxAnisotropyRet {
    int32_t result;
};
TexRefSetMaxAnisotropyRet tex_ref_set_max_anisotropy(uint64_t hTexRef, uint32_t maxAniso);

// ── cuTexRefSetBorderColor | enqueued ──
struct TexRefSetBorderColorRet {
    int32_t result;
};
TexRefSetBorderColorRet tex_ref_set_border_color(uint64_t hTexRef, uint64_t pBorderColor);

// ── cuTexRefSetFlags | enqueued ──
struct TexRefSetFlagsRet {
    int32_t result;
};
TexRefSetFlagsRet tex_ref_set_flags(uint64_t hTexRef, uint32_t Flags);

// ── cuTexRefGetArray | barrier ──
struct TexRefGetArrayRet {
    int32_t result;
    uint64_t phArray;  // PRODUCES handle
};
TexRefGetArrayRet tex_ref_get_array(uint64_t hTexRef);

// ── cuTexRefGetAddress | barrier ──
struct TexRefGetAddressRet {
    int32_t result;
    uint64_t pdptr;  // PRODUCES devptr
};
TexRefGetAddressRet tex_ref_get_address(uint64_t hTexRef);

// ── cuTexRefGetAddress_v2 | barrier ──
struct TexRefGetAddressV2Ret {
    int32_t result;
    uint64_t pdptr;  // PRODUCES devptr
};
TexRefGetAddressV2Ret tex_ref_get_address_v2(uint64_t hTexRef);

// ── cuTexRefGetFormat | barrier ──
struct TexRefGetFormatRet {
    int32_t result;
    uint32_t pfmt;
    int32_t pNumPackedComponents;
};
TexRefGetFormatRet tex_ref_get_format(uint64_t hTexRef);

// ── cuTexRefGetAddressMode | barrier ──
struct TexRefGetAddressModeRet {
    int32_t result;
    uint32_t pam;
};
TexRefGetAddressModeRet tex_ref_get_address_mode(uint64_t hTexRef, int32_t dim);

// ── cuTexRefGetFilterMode | barrier ──
struct TexRefGetFilterModeRet {
    int32_t result;
    uint32_t pfm;
};
TexRefGetFilterModeRet tex_ref_get_filter_mode(uint64_t hTexRef);

// ── cuTexRefGetMipmapFilterMode | barrier ──
struct TexRefGetMipmapFilterModeRet {
    int32_t result;
    uint32_t pfm;
};
TexRefGetMipmapFilterModeRet tex_ref_get_mipmap_filter_mode(uint64_t hTexRef);

// ── cuTexRefGetMipmapLevelBias | barrier ──
struct TexRefGetMipmapLevelBiasRet {
    int32_t result;
    float pbias;
};
TexRefGetMipmapLevelBiasRet tex_ref_get_mipmap_level_bias(uint64_t hTexRef);

// ── cuTexRefGetMipmapLevelClamp | barrier ──
struct TexRefGetMipmapLevelClampRet {
    int32_t result;
    float pminMipmapLevelClamp;
    float pmaxMipmapLevelClamp;
};
TexRefGetMipmapLevelClampRet tex_ref_get_mipmap_level_clamp(uint64_t hTexRef);

// ── cuTexRefGetMaxAnisotropy | barrier ──
struct TexRefGetMaxAnisotropyRet {
    int32_t result;
    int32_t pmaxAniso;
};
TexRefGetMaxAnisotropyRet tex_ref_get_max_anisotropy(uint64_t hTexRef);

// ── cuTexRefGetBorderColor | barrier ──
struct TexRefGetBorderColorRet {
    int32_t result;
    uint64_t pBorderColor;
};
TexRefGetBorderColorRet tex_ref_get_border_color(uint64_t hTexRef);

// ── cuTexRefGetFlags | barrier ──
struct TexRefGetFlagsRet {
    int32_t result;
    uint32_t pFlags;
};
TexRefGetFlagsRet tex_ref_get_flags(uint64_t hTexRef);

// ── cuSurfRefSetArray | enqueued ──
struct SurfRefSetArrayRet {
    int32_t result;
};
SurfRefSetArrayRet surf_ref_set_array(uint64_t hSurfRef, uint64_t hArray, uint32_t Flags);

// ── cuSurfRefGetArray | barrier ──
struct SurfRefGetArrayRet {
    int32_t result;
    uint64_t phArray;  // PRODUCES handle
};
SurfRefGetArrayRet surf_ref_get_array(uint64_t hSurfRef);

// ── cuArrayDestroy | enqueued ──
struct ArrayDestroyRet {
    int32_t result;
};
ArrayDestroyRet array_destroy(uint64_t hArray);

// ── cuMipmappedArrayGetLevel | barrier ──
struct MipmappedArrayGetLevelRet {
    int32_t result;
    uint64_t pLevelArray;  // PRODUCES handle
};
MipmappedArrayGetLevelRet mipmapped_array_get_level(uint64_t hMipmappedArray, uint32_t level);

// ── cuMipmappedArrayDestroy | enqueued ──
struct MipmappedArrayDestroyRet {
    int32_t result;
};
MipmappedArrayDestroyRet mipmapped_array_destroy(uint64_t hMipmappedArray);

// ── cuPointerGetAttribute | barrier ──
struct PointerGetAttributeRet {
    int32_t result;
    uint64_t data;
};
PointerGetAttributeRet pointer_get_attribute(uint32_t attribute, uint64_t ptr);

// ── cuPointerSetAttribute | enqueued ──
struct PointerSetAttributeRet {
    int32_t result;
};
PointerSetAttributeRet pointer_set_attribute(uint64_t value, uint32_t attribute, uint64_t ptr);

// ── cuDeviceCanAccessPeer | barrier ──
struct DeviceCanAccessPeerRet {
    int32_t result;
    int32_t canAccessPeer;
};
DeviceCanAccessPeerRet device_can_access_peer(int32_t dev, int32_t peerDev);

// ── cuCtxEnablePeerAccess | enqueued ──
struct CtxEnablePeerAccessRet {
    int32_t result;
};
CtxEnablePeerAccessRet ctx_enable_peer_access(uint64_t peerContext, uint32_t Flags);

// ── cuCtxDisablePeerAccess | enqueued ──
struct CtxDisablePeerAccessRet {
    int32_t result;
};
CtxDisablePeerAccessRet ctx_disable_peer_access(uint64_t peerContext);

// ── cuGraphCreate | barrier ──
struct GraphCreateRet {
    int32_t result;
    uint64_t phGraph;  // PRODUCES handle
};
GraphCreateRet graph_create(uint32_t flags);

// ── cuGraphDestroy | enqueued ──
struct GraphDestroyRet {
    int32_t result;
};
GraphDestroyRet graph_destroy(uint64_t hGraph);

// ── cuGraphAddMemcpyNode1D | barrier ──
struct GraphAddMemcpyNode1DRet {
    int32_t result;
    uint64_t phGraphNode;  // PRODUCES handle
};
GraphAddMemcpyNode1DRet graph_add_memcpy_node1_d(uint64_t hGraph, uint64_t dependencies, uint64_t numDependencies, uint64_t dst, uint64_t src, uint64_t count, uint64_t ctx);

// ── cuGraphAddEmptyNode | barrier ──
struct GraphAddEmptyNodeRet {
    int32_t result;
    uint64_t phGraphNode;  // PRODUCES handle
};
GraphAddEmptyNodeRet graph_add_empty_node(uint64_t hGraph, uint64_t dependencies, uint64_t numDependencies);

// ── cuGraphAddEventRecordNode | barrier ──
struct GraphAddEventRecordNodeRet {
    int32_t result;
    uint64_t phGraphNode;  // PRODUCES handle
};
GraphAddEventRecordNodeRet graph_add_event_record_node(uint64_t hGraph, uint64_t dependencies, uint64_t numDependencies, uint64_t hEvent);

// ── cuGraphAddEventWaitNode | barrier ──
struct GraphAddEventWaitNodeRet {
    int32_t result;
    uint64_t phGraphNode;  // PRODUCES handle
};
GraphAddEventWaitNodeRet graph_add_event_wait_node(uint64_t hGraph, uint64_t dependencies, uint64_t numDependencies, uint64_t hEvent);

// ── cuGraphAddChildGraphNode | barrier ──
struct GraphAddChildGraphNodeRet {
    int32_t result;
    uint64_t phGraphNode;  // PRODUCES handle
};
GraphAddChildGraphNodeRet graph_add_child_graph_node(uint64_t hGraph, uint64_t dependencies, uint64_t numDependencies, uint64_t childGraph);

// ── cuGraphNodeGetType | barrier ──
struct GraphNodeGetTypeRet {
    int32_t result;
    uint32_t type;
};
GraphNodeGetTypeRet graph_node_get_type(uint64_t hNode);

// ── cuGraphDestroyNode | enqueued ──
struct GraphDestroyNodeRet {
    int32_t result;
};
GraphDestroyNodeRet graph_destroy_node(uint64_t hNode);

// ── cuGraphInstantiateWithFlags | barrier ──
struct GraphInstantiateWithFlagsRet {
    int32_t result;
    uint64_t phGraphExec;  // PRODUCES handle
};
GraphInstantiateWithFlagsRet graph_instantiate_with_flags(uint64_t hGraph, uint64_t flags);

// ── cuGraphLaunch | enqueued ──
struct GraphLaunchRet {
    int32_t result;
};
GraphLaunchRet graph_launch(uint64_t hGraphExec, uint64_t hStream);

// ── cuGraphLaunch_ptsz | enqueued ──
struct GraphLaunchPtszRet {
    int32_t result;
};
GraphLaunchPtszRet graph_launch_ptsz(uint64_t hGraphExec, uint64_t hStream);

// ── cuGraphExecDestroy | enqueued ──
struct GraphExecDestroyRet {
    int32_t result;
};
GraphExecDestroyRet graph_exec_destroy(uint64_t hGraphExec);

// ── cuGraphClone | barrier ──
struct GraphCloneRet {
    int32_t result;
    uint64_t phGraphClone;  // PRODUCES handle
};
GraphCloneRet graph_clone(uint64_t originalGraph);

// ── cuGraphNodeFindInClone | barrier ──
struct GraphNodeFindInCloneRet {
    int32_t result;
    uint64_t phNode;  // PRODUCES handle
};
GraphNodeFindInCloneRet graph_node_find_in_clone(uint64_t hOriginalNode, uint64_t hClonedGraph);

// ── cuGraphExecEventRecordNodeSetEvent | enqueued ──
struct GraphExecEventRecordNodeSetEventRet {
    int32_t result;
};
GraphExecEventRecordNodeSetEventRet graph_exec_event_record_node_set_event(uint64_t hGraphExec, uint64_t hNode, uint64_t hEvent);

// ── cuGraphExecEventWaitNodeSetEvent | enqueued ──
struct GraphExecEventWaitNodeSetEventRet {
    int32_t result;
};
GraphExecEventWaitNodeSetEventRet graph_exec_event_wait_node_set_event(uint64_t hGraphExec, uint64_t hNode, uint64_t hEvent);

// ── cuGraphEventRecordNodeGetEvent | barrier ──
struct GraphEventRecordNodeGetEventRet {
    int32_t result;
    uint64_t hEvent_out;  // PRODUCES handle
};
GraphEventRecordNodeGetEventRet graph_event_record_node_get_event(uint64_t hNode);

// ── cuGraphEventWaitNodeGetEvent | barrier ──
struct GraphEventWaitNodeGetEventRet {
    int32_t result;
    uint64_t hEvent_out;  // PRODUCES handle
};
GraphEventWaitNodeGetEventRet graph_event_wait_node_get_event(uint64_t hNode);

// ── cuGraphUpload | enqueued ──
struct GraphUploadRet {
    int32_t result;
};
GraphUploadRet graph_upload(uint64_t hGraphExec, uint64_t hStream);

// ── cuStreamWriteValue32 | enqueued ──
struct StreamWriteValue32Ret {
    int32_t result;
};
StreamWriteValue32Ret stream_write_value32(uint64_t hStream, uint64_t addr, uint32_t value, uint32_t flags);

// ── cuStreamWriteValue32_ptsz | enqueued ──
struct StreamWriteValue32PtszRet {
    int32_t result;
};
StreamWriteValue32PtszRet stream_write_value32_ptsz(uint64_t hStream, uint64_t addr, uint32_t value, uint32_t flags);

// ── cuStreamWriteValue64 | enqueued ──
struct StreamWriteValue64Ret {
    int32_t result;
};
StreamWriteValue64Ret stream_write_value64(uint64_t hStream, uint64_t addr, uint64_t value, uint32_t flags);

// ── cuStreamWriteValue64_ptsz | enqueued ──
struct StreamWriteValue64PtszRet {
    int32_t result;
};
StreamWriteValue64PtszRet stream_write_value64_ptsz(uint64_t hStream, uint64_t addr, uint64_t value, uint32_t flags);

// ── cuStreamReadValue32 | barrier ──
struct StreamReadValue32Ret {
    int32_t result;
    uint32_t value;
};
StreamReadValue32Ret stream_read_value32(uint64_t hStream, uint64_t addr, uint32_t flags);

// ── cuStreamReadValue32_ptsz | barrier ──
struct StreamReadValue32PtszRet {
    int32_t result;
    uint32_t value;
};
StreamReadValue32PtszRet stream_read_value32_ptsz(uint64_t hStream, uint64_t addr, uint32_t flags);

// ── cuStreamReadValue64 | barrier ──
struct StreamReadValue64Ret {
    int32_t result;
    uint64_t value;
};
StreamReadValue64Ret stream_read_value64(uint64_t hStream, uint64_t addr, uint32_t flags);

// ── cuStreamReadValue64_ptsz | barrier ──
struct StreamReadValue64PtszRet {
    int32_t result;
    uint64_t value;
};
StreamReadValue64PtszRet stream_read_value64_ptsz(uint64_t hStream, uint64_t addr, uint32_t flags);

// ── cuProfilerInitialize | barrier ──
struct ProfilerInitializeRet {
    int32_t result;
};
ProfilerInitializeRet profiler_initialize(std::string configFile, std::string outputFile, uint32_t outputMode);

// ── cuProfilerStart | enqueued ──
struct ProfilerStartRet {
    int32_t result;
};
ProfilerStartRet profiler_start();

// ── cuProfilerStop | enqueued ──
struct ProfilerStopRet {
    int32_t result;
};
ProfilerStopRet profiler_stop();

// ── cuMemAdvise | enqueued ──
struct MemAdviseRet {
    int32_t result;
};
MemAdviseRet mem_advise(uint64_t dptr, uint64_t count, uint32_t advice, uint64_t location);

// ── cuMemAdvise_v2 | enqueued ──
struct MemAdviseV2Ret {
    int32_t result;
};
MemAdviseV2Ret mem_advise_v2(uint64_t dptr, uint64_t count, uint32_t advice, uint64_t location);

// ── cuMemPrefetchAsync | enqueued ──
struct MemPrefetchAsyncRet {
    int32_t result;
};
MemPrefetchAsyncRet mem_prefetch_async(uint64_t dptr, uint64_t count, uint64_t location, uint64_t hStream);

// ── cuMemPrefetchAsync_v2 | enqueued ──
struct MemPrefetchAsyncV2Ret {
    int32_t result;
};
MemPrefetchAsyncV2Ret mem_prefetch_async_v2(uint64_t dptr, uint64_t count, uint64_t location, uint32_t flags, uint64_t hStream);

// ── cuMemRangeGetAttribute | barrier ──
struct MemRangeGetAttributeRet {
    int32_t result;
    uint64_t data;
};
MemRangeGetAttributeRet mem_range_get_attribute(uint64_t dataSize, uint32_t attribute, uint64_t dptr, uint64_t count);

// ── cuFuncGetAttribute | barrier ──
struct FuncGetAttributeRet {
    int32_t result;
    int32_t value;
};
FuncGetAttributeRet func_get_attribute(uint32_t attrib, uint64_t hfunc);

// ── cuFuncSetAttribute | enqueued ──
struct FuncSetAttributeRet {
    int32_t result;
};
FuncSetAttributeRet func_set_attribute(uint64_t hfunc, uint32_t attrib, int32_t value);

// ── cuFuncSetCacheConfig | enqueued ──
struct FuncSetCacheConfigRet {
    int32_t result;
};
FuncSetCacheConfigRet func_set_cache_config(uint64_t hfunc, uint32_t config);

// ── cuFuncSetSharedMemConfig | enqueued ──
struct FuncSetSharedMemConfigRet {
    int32_t result;
};
FuncSetSharedMemConfigRet func_set_shared_mem_config(uint64_t hfunc, uint32_t config);

// ── cuFuncGetModule | barrier ──
struct FuncGetModuleRet {
    int32_t result;
    uint64_t hmod;  // PRODUCES handle
};
FuncGetModuleRet func_get_module(uint64_t hfunc);

// ── cuFuncGetName | barrier ──
struct FuncGetNameRet {
    int32_t result;
    std::string name;
};
FuncGetNameRet func_get_name(uint64_t hfunc);

// ── cuFuncIsLoaded | barrier ──
struct FuncIsLoadedRet {
    int32_t result;
    uint32_t state;
};
FuncIsLoadedRet func_is_loaded(uint64_t hfunc);

// ── cuFuncLoad | enqueued ──
struct FuncLoadRet {
    int32_t result;
};
FuncLoadRet func_load(uint64_t hfunc);

// ── cuLibraryLoadData | barrier ──
struct LibraryLoadDataRet {
    int32_t result;
    uint64_t library;  // PRODUCES handle
};
LibraryLoadDataRet library_load_data(uint64_t code, uint64_t jitOptions, uint64_t jitOptionValues, uint32_t numJitOptions);

// ── cuLibraryLoadFromFile | barrier ──
struct LibraryLoadFromFileRet {
    int32_t result;
    uint64_t library;  // PRODUCES handle
};
LibraryLoadFromFileRet library_load_from_file(std::string fileName, uint64_t jitOptions, uint64_t jitOptionValues, uint32_t numJitOptions);

// ── cuLibraryUnload | enqueued ──
struct LibraryUnloadRet {
    int32_t result;
};
LibraryUnloadRet library_unload(uint64_t library);

// ── cuLibraryGetKernel | barrier ──
struct LibraryGetKernelRet {
    int32_t result;
    uint64_t pKernel;  // PRODUCES handle
};
LibraryGetKernelRet library_get_kernel(uint64_t library, std::string name);

// ── cuLibraryGetModule | barrier ──
struct LibraryGetModuleRet {
    int32_t result;
    uint64_t pMod;  // PRODUCES handle
};
LibraryGetModuleRet library_get_module(uint64_t library);

// ── cuKernelGetFunction | barrier ──
struct KernelGetFunctionRet {
    int32_t result;
    uint64_t pFunc;  // PRODUCES handle
};
KernelGetFunctionRet kernel_get_function(uint64_t kernel);

// ── cuKernelGetAttribute | barrier ──
struct KernelGetAttributeRet {
    int32_t result;
    int32_t value;
};
KernelGetAttributeRet kernel_get_attribute(uint32_t attrib, uint64_t kernel);

// ── cuKernelSetAttribute | enqueued ──
struct KernelSetAttributeRet {
    int32_t result;
};
KernelSetAttributeRet kernel_set_attribute(uint32_t attrib, int32_t value, uint64_t kernel);

// ── cuKernelSetCacheConfig | enqueued ──
struct KernelSetCacheConfigRet {
    int32_t result;
};
KernelSetCacheConfigRet kernel_set_cache_config(uint64_t kernel, uint32_t config);

// ── cuLibraryGetGlobal | barrier ──
struct LibraryGetGlobalRet {
    int32_t result;
    uint64_t bytes;
    uint64_t dptr;  // PRODUCES devptr
};
LibraryGetGlobalRet library_get_global(uint64_t library, std::string name);

// ── cuLibraryGetManaged | barrier ──
struct LibraryGetManagedRet {
    int32_t result;
    uint64_t bytes;
    uint64_t dptr;  // PRODUCES devptr
};
LibraryGetManagedRet library_get_managed(uint64_t library, std::string name);

// ── cuLibraryGetUnifiedFunction | barrier ──
struct LibraryGetUnifiedFunctionRet {
    int32_t result;
    uint64_t pFunc;
};
LibraryGetUnifiedFunctionRet library_get_unified_function(uint64_t library, std::string name);

// ── cuMemcpy_ptds | enqueued ──
struct MemcpyPtdsRet {
    int32_t result;
};
MemcpyPtdsRet memcpy_ptds(uint64_t dst, uint64_t src, uint64_t ByteCount);

// ── cuMemcpyAsync_ptds | enqueued ──
struct MemcpyAsyncPtdsRet {
    int32_t result;
};
MemcpyAsyncPtdsRet memcpy_async_ptds(uint64_t dst, uint64_t src, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyHtoD_ptds | enqueued ──
struct MemcpyHtoDPtdsRet {
    int32_t result;
};
MemcpyHtoDPtdsRet memcpy_hto_d_ptds(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount);

// ── cuMemcpyDtoH_ptds | readback ──
struct MemcpyDtoHPtdsRet {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHPtdsRet memcpy_dto_h_ptds(uint64_t srcDevice, uint64_t ByteCount);

// ── cuMemcpyHtoDAsync_ptsz | enqueued ──
struct MemcpyHtoDAsyncPtszRet {
    int32_t result;
};
MemcpyHtoDAsyncPtszRet memcpy_hto_d_async_ptsz(uint64_t dstDevice, uint64_t srcHost, uint64_t ByteCount, uint64_t hStream);

// ── cuMemcpyDtoHAsync_ptsz | readback ──
struct MemcpyDtoHAsyncPtszRet {
    int32_t result;
    uint64_t dstHost;
};
MemcpyDtoHAsyncPtszRet memcpy_dto_h_async_ptsz(uint64_t srcDevice, uint64_t ByteCount, uint64_t hStream);

// ── cuMemsetD8_ptds | enqueued ──
struct MemsetD8PtdsRet {
    int32_t result;
};
MemsetD8PtdsRet memset_d8_ptds(uint64_t dstDevice, uint32_t uc, uint64_t N);

// ── cuMemsetD32_ptds | enqueued ──
struct MemsetD32PtdsRet {
    int32_t result;
};
MemsetD32PtdsRet memset_d32_ptds(uint64_t dstDevice, uint32_t ui, uint64_t N);

// ── cuMemsetD8Async_ptsz | enqueued ──
struct MemsetD8AsyncPtszRet {
    int32_t result;
};
MemsetD8AsyncPtszRet memset_d8_async_ptsz(uint64_t dstDevice, uint32_t uc, uint64_t N, uint64_t hStream);

// ── cuMemsetD32Async_ptsz | enqueued ──
struct MemsetD32AsyncPtszRet {
    int32_t result;
};
MemsetD32AsyncPtszRet memset_d32_async_ptsz(uint64_t dstDevice, uint32_t ui, uint64_t N, uint64_t hStream);

// ── cuStreamSynchronize_ptsz | barrier ──
struct StreamSynchronizePtszRet {
    int32_t result;
};
StreamSynchronizePtszRet stream_synchronize_ptsz(uint64_t hStream);

// ── cuCtxSynchronize_ptds | barrier ──
struct CtxSynchronizePtdsRet {
    int32_t result;
};
CtxSynchronizePtdsRet ctx_synchronize_ptds();

// ── cuGraphLaunch_ptsz | enqueued ──
struct GraphLaunchPtszRet {
    int32_t result;
};
GraphLaunchPtszRet graph_launch_ptsz(uint64_t hGraphExec, uint64_t hStream);

// ── cuMemAllocFromPoolAsync | barrier ──
struct MemAllocFromPoolAsyncRet {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocFromPoolAsyncRet mem_alloc_from_pool_async(uint64_t bytesize, uint64_t pool, uint64_t hStream);

// ── cuMemAllocFromPoolAsync_ptsz | barrier ──
struct MemAllocFromPoolAsyncPtszRet {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocFromPoolAsyncPtszRet mem_alloc_from_pool_async_ptsz(uint64_t bytesize, uint64_t pool, uint64_t hStream);

// ── cuMemAllocAsync | barrier ──
struct MemAllocAsyncRet {
    int32_t result;
    uint64_t dptr;  // PRODUCES devptr
};
MemAllocAsyncRet mem_alloc_async(uint64_t bytesize, uint64_t hStream);

// ── cuMemFreeAsync | enqueued ──
struct MemFreeAsyncRet {
    int32_t result;
};
MemFreeAsyncRet mem_free_async(uint64_t dptr, uint64_t hStream);

// ── cuMemPoolTrimTo | enqueued ──
struct MemPoolTrimToRet {
    int32_t result;
};
MemPoolTrimToRet mem_pool_trim_to(uint64_t pool, uint64_t minBytesToKeep);

// ── cuMemPoolSetAttribute | enqueued ──
struct MemPoolSetAttributeRet {
    int32_t result;
};
MemPoolSetAttributeRet mem_pool_set_attribute(uint64_t pool, uint32_t attr, uint64_t value);

// ── cuMemPoolGetAttribute | barrier ──
struct MemPoolGetAttributeRet {
    int32_t result;
    uint64_t value;
};
MemPoolGetAttributeRet mem_pool_get_attribute(uint64_t pool, uint32_t attr);

// ── cuMemPoolCreate | barrier ──
struct MemPoolCreateRet {
    int32_t result;
    uint64_t pool;  // PRODUCES handle
};
MemPoolCreateRet mem_pool_create(uint64_t poolProps);

// ── cuMemPoolDestroy | enqueued ──
struct MemPoolDestroyRet {
    int32_t result;
};
MemPoolDestroyRet mem_pool_destroy(uint64_t pool);

// ══════════════════════════════════════════════════════════════
// RPC binding — maps function indices to handlers
// ══════════════════════════════════════════════════════════════
using cuda_gen_rpc = zpp::bits::rpc<
    zpp::bits::bind<&cuda_gen::init, 0>,  // cuInit
    zpp::bits::bind<&cuda_gen::driver_get_version, 1>,  // cuDriverGetVersion
    zpp::bits::bind<&cuda_gen::device_get_count, 2>,  // cuDeviceGetCount
    zpp::bits::bind<&cuda_gen::device_get, 3>,  // cuDeviceGet
    zpp::bits::bind<&cuda_gen::device_get_name, 4>,  // cuDeviceGetName
    zpp::bits::bind<&cuda_gen::device_total_mem, 5>,  // cuDeviceTotalMem
    zpp::bits::bind<&cuda_gen::device_total_mem_v2, 6>,  // cuDeviceTotalMem_v2
    zpp::bits::bind<&cuda_gen::device_get_attribute, 7>,  // cuDeviceGetAttribute
    zpp::bits::bind<&cuda_gen::device_get_mem_pool, 8>,  // cuDeviceGetMemPool
    zpp::bits::bind<&cuda_gen::device_set_mem_pool, 9>,  // cuDeviceSetMemPool
    zpp::bits::bind<&cuda_gen::device_get_exec_affinity_support, 10>,  // cuDeviceGetExecAffinitySupport
    zpp::bits::bind<&cuda_gen::device_get_cuda_compute_capability, 11>,  // cuDeviceGetCudaComputeCapability
    zpp::bits::bind<&cuda_gen::device_primary_ctx_retain, 12>,  // cuDevicePrimaryCtxRetain
    zpp::bits::bind<&cuda_gen::device_primary_ctx_release, 13>,  // cuDevicePrimaryCtxRelease
    zpp::bits::bind<&cuda_gen::device_primary_ctx_release_v2, 14>,  // cuDevicePrimaryCtxRelease_v2
    zpp::bits::bind<&cuda_gen::device_primary_ctx_set_flags, 15>,  // cuDevicePrimaryCtxSetFlags
    zpp::bits::bind<&cuda_gen::device_primary_ctx_set_flags_v2, 16>,  // cuDevicePrimaryCtxSetFlags_v2
    zpp::bits::bind<&cuda_gen::device_primary_ctx_get_state, 17>,  // cuDevicePrimaryCtxGetState
    zpp::bits::bind<&cuda_gen::ctx_create, 18>,  // cuCtxCreate
    zpp::bits::bind<&cuda_gen::ctx_create_v2, 19>,  // cuCtxCreate_v2
    zpp::bits::bind<&cuda_gen::ctx_destroy, 20>,  // cuCtxDestroy
    zpp::bits::bind<&cuda_gen::ctx_destroy_v2, 21>,  // cuCtxDestroy_v2
    zpp::bits::bind<&cuda_gen::ctx_set_current, 22>,  // cuCtxSetCurrent
    zpp::bits::bind<&cuda_gen::ctx_get_current, 23>,  // cuCtxGetCurrent
    zpp::bits::bind<&cuda_gen::ctx_push_current, 24>,  // cuCtxPushCurrent
    zpp::bits::bind<&cuda_gen::ctx_push_current_v2, 25>,  // cuCtxPushCurrent_v2
    zpp::bits::bind<&cuda_gen::ctx_pop_current, 26>,  // cuCtxPopCurrent
    zpp::bits::bind<&cuda_gen::ctx_pop_current_v2, 27>,  // cuCtxPopCurrent_v2
    zpp::bits::bind<&cuda_gen::ctx_set_flags, 28>,  // cuCtxSetFlags
    zpp::bits::bind<&cuda_gen::ctx_set_flags_v2, 29>,  // cuCtxSetFlags_v2
    zpp::bits::bind<&cuda_gen::ctx_synchronize, 30>,  // cuCtxSynchronize
    zpp::bits::bind<&cuda_gen::ctx_get_device, 31>,  // cuCtxGetDevice
    zpp::bits::bind<&cuda_gen::ctx_get_flags, 32>,  // cuCtxGetFlags
    zpp::bits::bind<&cuda_gen::ctx_get_stream_priority_range, 33>,  // cuCtxGetStreamPriorityRange
    zpp::bits::bind<&cuda_gen::ctx_get_cache_config, 34>,  // cuCtxGetCacheConfig
    zpp::bits::bind<&cuda_gen::ctx_set_cache_config, 35>,  // cuCtxSetCacheConfig
    zpp::bits::bind<&cuda_gen::ctx_get_shared_mem_config, 36>,  // cuCtxGetSharedMemConfig
    zpp::bits::bind<&cuda_gen::ctx_set_shared_mem_config, 37>,  // cuCtxSetSharedMemConfig
    zpp::bits::bind<&cuda_gen::ctx_get_api_version, 38>,  // cuCtxGetApiVersion
    zpp::bits::bind<&cuda_gen::ctx_get_limit, 39>,  // cuCtxGetLimit
    zpp::bits::bind<&cuda_gen::ctx_set_limit, 40>,  // cuCtxSetLimit
    zpp::bits::bind<&cuda_gen::ctx_enable_peer_access, 191>,  // cuCtxEnablePeerAccess
    zpp::bits::bind<&cuda_gen::ctx_disable_peer_access, 192>,  // cuCtxDisablePeerAccess
    zpp::bits::bind<&cuda_gen::mem_alloc, 43>,  // cuMemAlloc
    zpp::bits::bind<&cuda_gen::mem_alloc_v2, 44>,  // cuMemAlloc_v2
    zpp::bits::bind<&cuda_gen::mem_alloc_managed, 45>,  // cuMemAllocManaged
    zpp::bits::bind<&cuda_gen::mem_alloc_managed_v2, 46>,  // cuMemAllocManaged_v2
    zpp::bits::bind<&cuda_gen::mem_free, 47>,  // cuMemFree
    zpp::bits::bind<&cuda_gen::mem_free_v2, 48>,  // cuMemFree_v2
    zpp::bits::bind<&cuda_gen::mem_free_host, 49>,  // cuMemFreeHost
    zpp::bits::bind<&cuda_gen::mem_host_alloc, 50>,  // cuMemHostAlloc
    zpp::bits::bind<&cuda_gen::mem_host_register, 51>,  // cuMemHostRegister
    zpp::bits::bind<&cuda_gen::mem_host_register_v2, 52>,  // cuMemHostRegister_v2
    zpp::bits::bind<&cuda_gen::mem_host_unregister, 53>,  // cuMemHostUnregister
    zpp::bits::bind<&cuda_gen::mem_host_get_device_pointer, 54>,  // cuMemHostGetDevicePointer
    zpp::bits::bind<&cuda_gen::mem_host_get_device_pointer_v2, 55>,  // cuMemHostGetDevicePointer_v2
    zpp::bits::bind<&cuda_gen::mem_host_get_flags, 56>,  // cuMemHostGetFlags
    zpp::bits::bind<&cuda_gen::mem_get_info, 57>,  // cuMemGetInfo
    zpp::bits::bind<&cuda_gen::mem_get_info_v2, 58>,  // cuMemGetInfo_v2
    zpp::bits::bind<&cuda_gen::mem_alloc_pitch, 59>,  // cuMemAllocPitch
    zpp::bits::bind<&cuda_gen::mem_alloc_pitch_v2, 60>,  // cuMemAllocPitch_v2
    zpp::bits::bind<&cuda_gen::memcpy_hto_d, 61>,  // cuMemcpyHtoD
    zpp::bits::bind<&cuda_gen::memcpy_hto_d_v2, 62>,  // cuMemcpyHtoD_v2
    zpp::bits::bind<&cuda_gen::memcpy_dto_h, 63>,  // cuMemcpyDtoH
    zpp::bits::bind<&cuda_gen::memcpy_dto_h_v2, 64>,  // cuMemcpyDtoH_v2
    zpp::bits::bind<&cuda_gen::memcpy_dto_d, 65>,  // cuMemcpyDtoD
    zpp::bits::bind<&cuda_gen::memcpy_dto_d_v2, 66>,  // cuMemcpyDtoD_v2
    zpp::bits::bind<&cuda_gen::memcpy_hto_d_async, 67>,  // cuMemcpyHtoDAsync
    zpp::bits::bind<&cuda_gen::memcpy_hto_d_async_v2, 68>,  // cuMemcpyHtoDAsync_v2
    zpp::bits::bind<&cuda_gen::memcpy_dto_h_async, 69>,  // cuMemcpyDtoHAsync
    zpp::bits::bind<&cuda_gen::memcpy_dto_h_async_v2, 70>,  // cuMemcpyDtoHAsync_v2
    zpp::bits::bind<&cuda_gen::memcpy_dto_d_async, 71>,  // cuMemcpyDtoDAsync
    zpp::bits::bind<&cuda_gen::memcpy_dto_d_async_v2, 72>,  // cuMemcpyDtoDAsync_v2
    zpp::bits::bind<&cuda_gen::memcpy, 73>,  // cuMemcpy
    zpp::bits::bind<&cuda_gen::memcpy_v2, 74>,  // cuMemcpy_v2
    zpp::bits::bind<&cuda_gen::memcpy_async, 75>,  // cuMemcpyAsync
    zpp::bits::bind<&cuda_gen::memcpy_peer, 76>,  // cuMemcpyPeer
    zpp::bits::bind<&cuda_gen::memcpy_peer_v2, 77>,  // cuMemcpyPeer_v2
    zpp::bits::bind<&cuda_gen::memcpy_peer_async, 78>,  // cuMemcpyPeerAsync
    zpp::bits::bind<&cuda_gen::memcpy_peer_async_v2, 79>,  // cuMemcpyPeerAsync_v2
    zpp::bits::bind<&cuda_gen::memset_d8, 80>,  // cuMemsetD8
    zpp::bits::bind<&cuda_gen::memset_d8_v2, 81>,  // cuMemsetD8_v2
    zpp::bits::bind<&cuda_gen::memset_d16, 82>,  // cuMemsetD16
    zpp::bits::bind<&cuda_gen::memset_d16_v2, 83>,  // cuMemsetD16_v2
    zpp::bits::bind<&cuda_gen::memset_d32, 84>,  // cuMemsetD32
    zpp::bits::bind<&cuda_gen::memset_d32_v2, 85>,  // cuMemsetD32_v2
    zpp::bits::bind<&cuda_gen::memset_d2_d8, 86>,  // cuMemsetD2D8
    zpp::bits::bind<&cuda_gen::memset_d2_d8_v2, 87>,  // cuMemsetD2D8_v2
    zpp::bits::bind<&cuda_gen::memset_d2_d16, 88>,  // cuMemsetD2D16
    zpp::bits::bind<&cuda_gen::memset_d2_d16_v2, 89>,  // cuMemsetD2D16_v2
    zpp::bits::bind<&cuda_gen::memset_d2_d32, 90>,  // cuMemsetD2D32
    zpp::bits::bind<&cuda_gen::memset_d2_d32_v2, 91>,  // cuMemsetD2D32_v2
    zpp::bits::bind<&cuda_gen::memset_d8_async, 92>,  // cuMemsetD8Async
    zpp::bits::bind<&cuda_gen::memset_d16_async, 93>,  // cuMemsetD16Async
    zpp::bits::bind<&cuda_gen::memset_d32_async, 94>,  // cuMemsetD32Async
    zpp::bits::bind<&cuda_gen::memset_d2_d8_async, 95>,  // cuMemsetD2D8Async
    zpp::bits::bind<&cuda_gen::memset_d2_d16_async, 96>,  // cuMemsetD2D16Async
    zpp::bits::bind<&cuda_gen::memset_d2_d32_async, 97>,  // cuMemsetD2D32Async
    zpp::bits::bind<&cuda_gen::mem_address_reserve, 98>,  // cuMemAddressReserve
    zpp::bits::bind<&cuda_gen::mem_address_free, 99>,  // cuMemAddressFree
    zpp::bits::bind<&cuda_gen::mem_create, 100>,  // cuMemCreate
    zpp::bits::bind<&cuda_gen::mem_release, 101>,  // cuMemRelease
    zpp::bits::bind<&cuda_gen::mem_map, 102>,  // cuMemMap
    zpp::bits::bind<&cuda_gen::mem_unmap, 103>,  // cuMemUnmap
    zpp::bits::bind<&cuda_gen::mem_set_access, 104>,  // cuMemSetAccess
    zpp::bits::bind<&cuda_gen::mem_get_access, 105>,  // cuMemGetAccess
    zpp::bits::bind<&cuda_gen::mem_get_allocation_granularity, 106>,  // cuMemGetAllocationGranularity
    zpp::bits::bind<&cuda_gen::mem_retain_allocation_handle, 107>,  // cuMemRetainAllocationHandle
    zpp::bits::bind<&cuda_gen::module_load, 108>,  // cuModuleLoad
    zpp::bits::bind<&cuda_gen::module_load_data, 109>,  // cuModuleLoadData
    zpp::bits::bind<&cuda_gen::module_load_data_ex, 110>,  // cuModuleLoadDataEx
    zpp::bits::bind<&cuda_gen::module_load_fat_binary, 111>,  // cuModuleLoadFatBinary
    zpp::bits::bind<&cuda_gen::module_unload, 112>,  // cuModuleUnload
    zpp::bits::bind<&cuda_gen::module_get_function, 113>,  // cuModuleGetFunction
    zpp::bits::bind<&cuda_gen::module_get_global, 114>,  // cuModuleGetGlobal
    zpp::bits::bind<&cuda_gen::module_get_global_v2, 115>,  // cuModuleGetGlobal_v2
    zpp::bits::bind<&cuda_gen::module_get_tex_ref, 116>,  // cuModuleGetTexRef
    zpp::bits::bind<&cuda_gen::module_get_surf_ref, 117>,  // cuModuleGetSurfRef
    zpp::bits::bind<&cuda_gen::launch_kernel, 118>,  // cuLaunchKernel
    zpp::bits::bind<&cuda_gen::launch_cooperative_kernel, 119>,  // cuLaunchCooperativeKernel
    zpp::bits::bind<&cuda_gen::launch_host_func, 120>,  // cuLaunchHostFunc
    zpp::bits::bind<&cuda_gen::get_proc_address, 121>,  // cuGetProcAddress
    zpp::bits::bind<&cuda_gen::get_proc_address_v2, 122>,  // cuGetProcAddress_v2
    zpp::bits::bind<&cuda_gen::stream_create, 123>,  // cuStreamCreate
    zpp::bits::bind<&cuda_gen::stream_create_with_priority, 124>,  // cuStreamCreateWithPriority
    zpp::bits::bind<&cuda_gen::stream_destroy, 125>,  // cuStreamDestroy
    zpp::bits::bind<&cuda_gen::stream_destroy_v2, 126>,  // cuStreamDestroy_v2
    zpp::bits::bind<&cuda_gen::stream_synchronize, 127>,  // cuStreamSynchronize
    zpp::bits::bind<&cuda_gen::stream_get_priority, 128>,  // cuStreamGetPriority
    zpp::bits::bind<&cuda_gen::stream_get_flags, 129>,  // cuStreamGetFlags
    zpp::bits::bind<&cuda_gen::stream_get_ctx, 130>,  // cuStreamGetCtx
    zpp::bits::bind<&cuda_gen::stream_wait_event, 131>,  // cuStreamWaitEvent
    zpp::bits::bind<&cuda_gen::stream_wait_event_ptsz, 132>,  // cuStreamWaitEvent_ptsz
    zpp::bits::bind<&cuda_gen::stream_add_callback, 133>,  // cuStreamAddCallback
    zpp::bits::bind<&cuda_gen::stream_add_callback_ptsz, 134>,  // cuStreamAddCallback_ptsz
    zpp::bits::bind<&cuda_gen::stream_begin_capture, 135>,  // cuStreamBeginCapture
    zpp::bits::bind<&cuda_gen::stream_begin_capture_ptsz, 136>,  // cuStreamBeginCapture_ptsz
    zpp::bits::bind<&cuda_gen::stream_end_capture, 137>,  // cuStreamEndCapture
    zpp::bits::bind<&cuda_gen::stream_end_capture_ptsz, 138>,  // cuStreamEndCapture_ptsz
    zpp::bits::bind<&cuda_gen::stream_is_capturing, 139>,  // cuStreamIsCapturing
    zpp::bits::bind<&cuda_gen::stream_attach_mem_async, 140>,  // cuStreamAttachMemAsync
    zpp::bits::bind<&cuda_gen::stream_attach_mem_async_ptsz, 141>,  // cuStreamAttachMemAsync_ptsz
    zpp::bits::bind<&cuda_gen::stream_query, 142>,  // cuStreamQuery
    zpp::bits::bind<&cuda_gen::stream_query_ptsz, 143>,  // cuStreamQuery_ptsz
    zpp::bits::bind<&cuda_gen::event_create, 144>,  // cuEventCreate
    zpp::bits::bind<&cuda_gen::event_record, 145>,  // cuEventRecord
    zpp::bits::bind<&cuda_gen::event_record_ptsz, 146>,  // cuEventRecord_ptsz
    zpp::bits::bind<&cuda_gen::event_record_with_flags, 147>,  // cuEventRecordWithFlags
    zpp::bits::bind<&cuda_gen::event_record_with_flags_ptsz, 148>,  // cuEventRecordWithFlags_ptsz
    zpp::bits::bind<&cuda_gen::event_destroy, 149>,  // cuEventDestroy
    zpp::bits::bind<&cuda_gen::event_destroy_v2, 150>,  // cuEventDestroy_v2
    zpp::bits::bind<&cuda_gen::event_synchronize, 151>,  // cuEventSynchronize
    zpp::bits::bind<&cuda_gen::event_elapsed_time, 152>,  // cuEventElapsedTime
    zpp::bits::bind<&cuda_gen::event_query, 153>,  // cuEventQuery
    zpp::bits::bind<&cuda_gen::occupancy_max_active_blocks_per_multiprocessor, 154>,  // cuOccupancyMaxActiveBlocksPerMultiprocessor
    zpp::bits::bind<&cuda_gen::occupancy_max_active_blocks_per_multiprocessor_with_flags, 155>,  // cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    zpp::bits::bind<&cuda_gen::occupancy_max_potential_block_size, 156>,  // cuOccupancyMaxPotentialBlockSize
    zpp::bits::bind<&cuda_gen::occupancy_max_potential_block_size_with_flags, 157>,  // cuOccupancyMaxPotentialBlockSizeWithFlags
    zpp::bits::bind<&cuda_gen::occupancy_available_dynamic_s_mem_per_block, 158>,  // cuOccupancyAvailableDynamicSMemPerBlock
    zpp::bits::bind<&cuda_gen::tex_ref_set_array, 159>,  // cuTexRefSetArray
    zpp::bits::bind<&cuda_gen::tex_ref_set_address, 160>,  // cuTexRefSetAddress
    zpp::bits::bind<&cuda_gen::tex_ref_set_address_v2, 161>,  // cuTexRefSetAddress_v2
    zpp::bits::bind<&cuda_gen::tex_ref_set_format, 162>,  // cuTexRefSetFormat
    zpp::bits::bind<&cuda_gen::tex_ref_set_address_mode, 163>,  // cuTexRefSetAddressMode
    zpp::bits::bind<&cuda_gen::tex_ref_set_filter_mode, 164>,  // cuTexRefSetFilterMode
    zpp::bits::bind<&cuda_gen::tex_ref_set_mipmap_filter_mode, 165>,  // cuTexRefSetMipmapFilterMode
    zpp::bits::bind<&cuda_gen::tex_ref_set_mipmap_level_bias, 166>,  // cuTexRefSetMipmapLevelBias
    zpp::bits::bind<&cuda_gen::tex_ref_set_mipmap_level_clamp, 167>,  // cuTexRefSetMipmapLevelClamp
    zpp::bits::bind<&cuda_gen::tex_ref_set_max_anisotropy, 168>,  // cuTexRefSetMaxAnisotropy
    zpp::bits::bind<&cuda_gen::tex_ref_set_border_color, 169>,  // cuTexRefSetBorderColor
    zpp::bits::bind<&cuda_gen::tex_ref_set_flags, 170>,  // cuTexRefSetFlags
    zpp::bits::bind<&cuda_gen::tex_ref_get_array, 171>,  // cuTexRefGetArray
    zpp::bits::bind<&cuda_gen::tex_ref_get_address, 172>,  // cuTexRefGetAddress
    zpp::bits::bind<&cuda_gen::tex_ref_get_address_v2, 173>,  // cuTexRefGetAddress_v2
    zpp::bits::bind<&cuda_gen::tex_ref_get_format, 174>,  // cuTexRefGetFormat
    zpp::bits::bind<&cuda_gen::tex_ref_get_address_mode, 175>,  // cuTexRefGetAddressMode
    zpp::bits::bind<&cuda_gen::tex_ref_get_filter_mode, 176>,  // cuTexRefGetFilterMode
    zpp::bits::bind<&cuda_gen::tex_ref_get_mipmap_filter_mode, 177>,  // cuTexRefGetMipmapFilterMode
    zpp::bits::bind<&cuda_gen::tex_ref_get_mipmap_level_bias, 178>,  // cuTexRefGetMipmapLevelBias
    zpp::bits::bind<&cuda_gen::tex_ref_get_mipmap_level_clamp, 179>,  // cuTexRefGetMipmapLevelClamp
    zpp::bits::bind<&cuda_gen::tex_ref_get_max_anisotropy, 180>,  // cuTexRefGetMaxAnisotropy
    zpp::bits::bind<&cuda_gen::tex_ref_get_border_color, 181>,  // cuTexRefGetBorderColor
    zpp::bits::bind<&cuda_gen::tex_ref_get_flags, 182>,  // cuTexRefGetFlags
    zpp::bits::bind<&cuda_gen::surf_ref_set_array, 183>,  // cuSurfRefSetArray
    zpp::bits::bind<&cuda_gen::surf_ref_get_array, 184>,  // cuSurfRefGetArray
    zpp::bits::bind<&cuda_gen::array_destroy, 185>,  // cuArrayDestroy
    zpp::bits::bind<&cuda_gen::mipmapped_array_get_level, 186>,  // cuMipmappedArrayGetLevel
    zpp::bits::bind<&cuda_gen::mipmapped_array_destroy, 187>,  // cuMipmappedArrayDestroy
    zpp::bits::bind<&cuda_gen::pointer_get_attribute, 188>,  // cuPointerGetAttribute
    zpp::bits::bind<&cuda_gen::pointer_set_attribute, 189>,  // cuPointerSetAttribute
    zpp::bits::bind<&cuda_gen::device_can_access_peer, 190>,  // cuDeviceCanAccessPeer
    zpp::bits::bind<&cuda_gen::ctx_enable_peer_access, 191>,  // cuCtxEnablePeerAccess
    zpp::bits::bind<&cuda_gen::ctx_disable_peer_access, 192>,  // cuCtxDisablePeerAccess
    zpp::bits::bind<&cuda_gen::graph_create, 193>,  // cuGraphCreate
    zpp::bits::bind<&cuda_gen::graph_destroy, 194>,  // cuGraphDestroy
    zpp::bits::bind<&cuda_gen::graph_add_memcpy_node1_d, 195>,  // cuGraphAddMemcpyNode1D
    zpp::bits::bind<&cuda_gen::graph_add_empty_node, 196>,  // cuGraphAddEmptyNode
    zpp::bits::bind<&cuda_gen::graph_add_event_record_node, 197>,  // cuGraphAddEventRecordNode
    zpp::bits::bind<&cuda_gen::graph_add_event_wait_node, 198>,  // cuGraphAddEventWaitNode
    zpp::bits::bind<&cuda_gen::graph_add_child_graph_node, 199>,  // cuGraphAddChildGraphNode
    zpp::bits::bind<&cuda_gen::graph_node_get_type, 200>,  // cuGraphNodeGetType
    zpp::bits::bind<&cuda_gen::graph_destroy_node, 201>,  // cuGraphDestroyNode
    zpp::bits::bind<&cuda_gen::graph_instantiate_with_flags, 202>,  // cuGraphInstantiateWithFlags
    zpp::bits::bind<&cuda_gen::graph_launch, 203>,  // cuGraphLaunch
    zpp::bits::bind<&cuda_gen::graph_launch_ptsz, 261>,  // cuGraphLaunch_ptsz
    zpp::bits::bind<&cuda_gen::graph_exec_destroy, 205>,  // cuGraphExecDestroy
    zpp::bits::bind<&cuda_gen::graph_clone, 206>,  // cuGraphClone
    zpp::bits::bind<&cuda_gen::graph_node_find_in_clone, 207>,  // cuGraphNodeFindInClone
    zpp::bits::bind<&cuda_gen::graph_exec_event_record_node_set_event, 208>,  // cuGraphExecEventRecordNodeSetEvent
    zpp::bits::bind<&cuda_gen::graph_exec_event_wait_node_set_event, 209>,  // cuGraphExecEventWaitNodeSetEvent
    zpp::bits::bind<&cuda_gen::graph_event_record_node_get_event, 210>,  // cuGraphEventRecordNodeGetEvent
    zpp::bits::bind<&cuda_gen::graph_event_wait_node_get_event, 211>,  // cuGraphEventWaitNodeGetEvent
    zpp::bits::bind<&cuda_gen::graph_upload, 212>,  // cuGraphUpload
    zpp::bits::bind<&cuda_gen::stream_write_value32, 213>,  // cuStreamWriteValue32
    zpp::bits::bind<&cuda_gen::stream_write_value32_ptsz, 214>,  // cuStreamWriteValue32_ptsz
    zpp::bits::bind<&cuda_gen::stream_write_value64, 215>,  // cuStreamWriteValue64
    zpp::bits::bind<&cuda_gen::stream_write_value64_ptsz, 216>,  // cuStreamWriteValue64_ptsz
    zpp::bits::bind<&cuda_gen::stream_read_value32, 217>,  // cuStreamReadValue32
    zpp::bits::bind<&cuda_gen::stream_read_value32_ptsz, 218>,  // cuStreamReadValue32_ptsz
    zpp::bits::bind<&cuda_gen::stream_read_value64, 219>,  // cuStreamReadValue64
    zpp::bits::bind<&cuda_gen::stream_read_value64_ptsz, 220>,  // cuStreamReadValue64_ptsz
    zpp::bits::bind<&cuda_gen::profiler_initialize, 221>,  // cuProfilerInitialize
    zpp::bits::bind<&cuda_gen::profiler_start, 222>,  // cuProfilerStart
    zpp::bits::bind<&cuda_gen::profiler_stop, 223>,  // cuProfilerStop
    zpp::bits::bind<&cuda_gen::mem_advise, 224>,  // cuMemAdvise
    zpp::bits::bind<&cuda_gen::mem_advise_v2, 225>,  // cuMemAdvise_v2
    zpp::bits::bind<&cuda_gen::mem_prefetch_async, 226>,  // cuMemPrefetchAsync
    zpp::bits::bind<&cuda_gen::mem_prefetch_async_v2, 227>,  // cuMemPrefetchAsync_v2
    zpp::bits::bind<&cuda_gen::mem_range_get_attribute, 228>,  // cuMemRangeGetAttribute
    zpp::bits::bind<&cuda_gen::func_get_attribute, 229>,  // cuFuncGetAttribute
    zpp::bits::bind<&cuda_gen::func_set_attribute, 230>,  // cuFuncSetAttribute
    zpp::bits::bind<&cuda_gen::func_set_cache_config, 231>,  // cuFuncSetCacheConfig
    zpp::bits::bind<&cuda_gen::func_set_shared_mem_config, 232>,  // cuFuncSetSharedMemConfig
    zpp::bits::bind<&cuda_gen::func_get_module, 233>,  // cuFuncGetModule
    zpp::bits::bind<&cuda_gen::func_get_name, 234>,  // cuFuncGetName
    zpp::bits::bind<&cuda_gen::func_is_loaded, 235>,  // cuFuncIsLoaded
    zpp::bits::bind<&cuda_gen::func_load, 236>,  // cuFuncLoad
    zpp::bits::bind<&cuda_gen::library_load_data, 237>,  // cuLibraryLoadData
    zpp::bits::bind<&cuda_gen::library_load_from_file, 238>,  // cuLibraryLoadFromFile
    zpp::bits::bind<&cuda_gen::library_unload, 239>,  // cuLibraryUnload
    zpp::bits::bind<&cuda_gen::library_get_kernel, 240>,  // cuLibraryGetKernel
    zpp::bits::bind<&cuda_gen::library_get_module, 241>,  // cuLibraryGetModule
    zpp::bits::bind<&cuda_gen::kernel_get_function, 242>,  // cuKernelGetFunction
    zpp::bits::bind<&cuda_gen::kernel_get_attribute, 243>,  // cuKernelGetAttribute
    zpp::bits::bind<&cuda_gen::kernel_set_attribute, 244>,  // cuKernelSetAttribute
    zpp::bits::bind<&cuda_gen::kernel_set_cache_config, 245>,  // cuKernelSetCacheConfig
    zpp::bits::bind<&cuda_gen::library_get_global, 246>,  // cuLibraryGetGlobal
    zpp::bits::bind<&cuda_gen::library_get_managed, 247>,  // cuLibraryGetManaged
    zpp::bits::bind<&cuda_gen::library_get_unified_function, 248>,  // cuLibraryGetUnifiedFunction
    zpp::bits::bind<&cuda_gen::memcpy_ptds, 249>,  // cuMemcpy_ptds
    zpp::bits::bind<&cuda_gen::memcpy_async_ptds, 250>,  // cuMemcpyAsync_ptds
    zpp::bits::bind<&cuda_gen::memcpy_hto_d_ptds, 251>,  // cuMemcpyHtoD_ptds
    zpp::bits::bind<&cuda_gen::memcpy_dto_h_ptds, 252>,  // cuMemcpyDtoH_ptds
    zpp::bits::bind<&cuda_gen::memcpy_hto_d_async_ptsz, 253>,  // cuMemcpyHtoDAsync_ptsz
    zpp::bits::bind<&cuda_gen::memcpy_dto_h_async_ptsz, 254>,  // cuMemcpyDtoHAsync_ptsz
    zpp::bits::bind<&cuda_gen::memset_d8_ptds, 255>,  // cuMemsetD8_ptds
    zpp::bits::bind<&cuda_gen::memset_d32_ptds, 256>,  // cuMemsetD32_ptds
    zpp::bits::bind<&cuda_gen::memset_d8_async_ptsz, 257>,  // cuMemsetD8Async_ptsz
    zpp::bits::bind<&cuda_gen::memset_d32_async_ptsz, 258>,  // cuMemsetD32Async_ptsz
    zpp::bits::bind<&cuda_gen::stream_synchronize_ptsz, 259>,  // cuStreamSynchronize_ptsz
    zpp::bits::bind<&cuda_gen::ctx_synchronize_ptds, 260>,  // cuCtxSynchronize_ptds
    zpp::bits::bind<&cuda_gen::graph_launch_ptsz, 261>,  // cuGraphLaunch_ptsz
    zpp::bits::bind<&cuda_gen::mem_alloc_from_pool_async, 262>,  // cuMemAllocFromPoolAsync
    zpp::bits::bind<&cuda_gen::mem_alloc_from_pool_async_ptsz, 263>,  // cuMemAllocFromPoolAsync_ptsz
    zpp::bits::bind<&cuda_gen::mem_alloc_async, 264>,  // cuMemAllocAsync
    zpp::bits::bind<&cuda_gen::mem_free_async, 265>,  // cuMemFreeAsync
    zpp::bits::bind<&cuda_gen::mem_pool_trim_to, 266>,  // cuMemPoolTrimTo
    zpp::bits::bind<&cuda_gen::mem_pool_set_attribute, 267>,  // cuMemPoolSetAttribute
    zpp::bits::bind<&cuda_gen::mem_pool_get_attribute, 268>,  // cuMemPoolGetAttribute
    zpp::bits::bind<&cuda_gen::mem_pool_create, 269>,  // cuMemPoolCreate
    zpp::bits::bind<&cuda_gen::mem_pool_destroy, 270>  // cuMemPoolDestroy
>;

// ── Named function indices ───────────────────────────────
namespace func_index {
    constexpr int init = 0;  // cuInit
    constexpr int driver_get_version = 1;  // cuDriverGetVersion
    constexpr int device_get_count = 2;  // cuDeviceGetCount
    constexpr int device_get = 3;  // cuDeviceGet
    constexpr int device_get_name = 4;  // cuDeviceGetName
    constexpr int device_total_mem = 5;  // cuDeviceTotalMem
    constexpr int device_total_mem_v2 = 6;  // cuDeviceTotalMem_v2
    constexpr int device_get_attribute = 7;  // cuDeviceGetAttribute
    constexpr int device_get_mem_pool = 8;  // cuDeviceGetMemPool
    constexpr int device_set_mem_pool = 9;  // cuDeviceSetMemPool
    constexpr int device_get_exec_affinity_support = 10;  // cuDeviceGetExecAffinitySupport
    constexpr int device_get_cuda_compute_capability = 11;  // cuDeviceGetCudaComputeCapability
    constexpr int device_primary_ctx_retain = 12;  // cuDevicePrimaryCtxRetain
    constexpr int device_primary_ctx_release = 13;  // cuDevicePrimaryCtxRelease
    constexpr int device_primary_ctx_release_v2 = 14;  // cuDevicePrimaryCtxRelease_v2
    constexpr int device_primary_ctx_set_flags = 15;  // cuDevicePrimaryCtxSetFlags
    constexpr int device_primary_ctx_set_flags_v2 = 16;  // cuDevicePrimaryCtxSetFlags_v2
    constexpr int device_primary_ctx_get_state = 17;  // cuDevicePrimaryCtxGetState
    constexpr int ctx_create = 18;  // cuCtxCreate
    constexpr int ctx_create_v2 = 19;  // cuCtxCreate_v2
    constexpr int ctx_destroy = 20;  // cuCtxDestroy
    constexpr int ctx_destroy_v2 = 21;  // cuCtxDestroy_v2
    constexpr int ctx_set_current = 22;  // cuCtxSetCurrent
    constexpr int ctx_get_current = 23;  // cuCtxGetCurrent
    constexpr int ctx_push_current = 24;  // cuCtxPushCurrent
    constexpr int ctx_push_current_v2 = 25;  // cuCtxPushCurrent_v2
    constexpr int ctx_pop_current = 26;  // cuCtxPopCurrent
    constexpr int ctx_pop_current_v2 = 27;  // cuCtxPopCurrent_v2
    constexpr int ctx_set_flags = 28;  // cuCtxSetFlags
    constexpr int ctx_set_flags_v2 = 29;  // cuCtxSetFlags_v2
    constexpr int ctx_synchronize = 30;  // cuCtxSynchronize
    constexpr int ctx_get_device = 31;  // cuCtxGetDevice
    constexpr int ctx_get_flags = 32;  // cuCtxGetFlags
    constexpr int ctx_get_stream_priority_range = 33;  // cuCtxGetStreamPriorityRange
    constexpr int ctx_get_cache_config = 34;  // cuCtxGetCacheConfig
    constexpr int ctx_set_cache_config = 35;  // cuCtxSetCacheConfig
    constexpr int ctx_get_shared_mem_config = 36;  // cuCtxGetSharedMemConfig
    constexpr int ctx_set_shared_mem_config = 37;  // cuCtxSetSharedMemConfig
    constexpr int ctx_get_api_version = 38;  // cuCtxGetApiVersion
    constexpr int ctx_get_limit = 39;  // cuCtxGetLimit
    constexpr int ctx_set_limit = 40;  // cuCtxSetLimit
    constexpr int ctx_enable_peer_access = 191;  // cuCtxEnablePeerAccess
    constexpr int ctx_disable_peer_access = 192;  // cuCtxDisablePeerAccess
    constexpr int mem_alloc = 43;  // cuMemAlloc
    constexpr int mem_alloc_v2 = 44;  // cuMemAlloc_v2
    constexpr int mem_alloc_managed = 45;  // cuMemAllocManaged
    constexpr int mem_alloc_managed_v2 = 46;  // cuMemAllocManaged_v2
    constexpr int mem_free = 47;  // cuMemFree
    constexpr int mem_free_v2 = 48;  // cuMemFree_v2
    constexpr int mem_free_host = 49;  // cuMemFreeHost
    constexpr int mem_host_alloc = 50;  // cuMemHostAlloc
    constexpr int mem_host_register = 51;  // cuMemHostRegister
    constexpr int mem_host_register_v2 = 52;  // cuMemHostRegister_v2
    constexpr int mem_host_unregister = 53;  // cuMemHostUnregister
    constexpr int mem_host_get_device_pointer = 54;  // cuMemHostGetDevicePointer
    constexpr int mem_host_get_device_pointer_v2 = 55;  // cuMemHostGetDevicePointer_v2
    constexpr int mem_host_get_flags = 56;  // cuMemHostGetFlags
    constexpr int mem_get_info = 57;  // cuMemGetInfo
    constexpr int mem_get_info_v2 = 58;  // cuMemGetInfo_v2
    constexpr int mem_alloc_pitch = 59;  // cuMemAllocPitch
    constexpr int mem_alloc_pitch_v2 = 60;  // cuMemAllocPitch_v2
    constexpr int memcpy_hto_d = 61;  // cuMemcpyHtoD
    constexpr int memcpy_hto_d_v2 = 62;  // cuMemcpyHtoD_v2
    constexpr int memcpy_dto_h = 63;  // cuMemcpyDtoH
    constexpr int memcpy_dto_h_v2 = 64;  // cuMemcpyDtoH_v2
    constexpr int memcpy_dto_d = 65;  // cuMemcpyDtoD
    constexpr int memcpy_dto_d_v2 = 66;  // cuMemcpyDtoD_v2
    constexpr int memcpy_hto_d_async = 67;  // cuMemcpyHtoDAsync
    constexpr int memcpy_hto_d_async_v2 = 68;  // cuMemcpyHtoDAsync_v2
    constexpr int memcpy_dto_h_async = 69;  // cuMemcpyDtoHAsync
    constexpr int memcpy_dto_h_async_v2 = 70;  // cuMemcpyDtoHAsync_v2
    constexpr int memcpy_dto_d_async = 71;  // cuMemcpyDtoDAsync
    constexpr int memcpy_dto_d_async_v2 = 72;  // cuMemcpyDtoDAsync_v2
    constexpr int memcpy = 73;  // cuMemcpy
    constexpr int memcpy_v2 = 74;  // cuMemcpy_v2
    constexpr int memcpy_async = 75;  // cuMemcpyAsync
    constexpr int memcpy_peer = 76;  // cuMemcpyPeer
    constexpr int memcpy_peer_v2 = 77;  // cuMemcpyPeer_v2
    constexpr int memcpy_peer_async = 78;  // cuMemcpyPeerAsync
    constexpr int memcpy_peer_async_v2 = 79;  // cuMemcpyPeerAsync_v2
    constexpr int memset_d8 = 80;  // cuMemsetD8
    constexpr int memset_d8_v2 = 81;  // cuMemsetD8_v2
    constexpr int memset_d16 = 82;  // cuMemsetD16
    constexpr int memset_d16_v2 = 83;  // cuMemsetD16_v2
    constexpr int memset_d32 = 84;  // cuMemsetD32
    constexpr int memset_d32_v2 = 85;  // cuMemsetD32_v2
    constexpr int memset_d2_d8 = 86;  // cuMemsetD2D8
    constexpr int memset_d2_d8_v2 = 87;  // cuMemsetD2D8_v2
    constexpr int memset_d2_d16 = 88;  // cuMemsetD2D16
    constexpr int memset_d2_d16_v2 = 89;  // cuMemsetD2D16_v2
    constexpr int memset_d2_d32 = 90;  // cuMemsetD2D32
    constexpr int memset_d2_d32_v2 = 91;  // cuMemsetD2D32_v2
    constexpr int memset_d8_async = 92;  // cuMemsetD8Async
    constexpr int memset_d16_async = 93;  // cuMemsetD16Async
    constexpr int memset_d32_async = 94;  // cuMemsetD32Async
    constexpr int memset_d2_d8_async = 95;  // cuMemsetD2D8Async
    constexpr int memset_d2_d16_async = 96;  // cuMemsetD2D16Async
    constexpr int memset_d2_d32_async = 97;  // cuMemsetD2D32Async
    constexpr int mem_address_reserve = 98;  // cuMemAddressReserve
    constexpr int mem_address_free = 99;  // cuMemAddressFree
    constexpr int mem_create = 100;  // cuMemCreate
    constexpr int mem_release = 101;  // cuMemRelease
    constexpr int mem_map = 102;  // cuMemMap
    constexpr int mem_unmap = 103;  // cuMemUnmap
    constexpr int mem_set_access = 104;  // cuMemSetAccess
    constexpr int mem_get_access = 105;  // cuMemGetAccess
    constexpr int mem_get_allocation_granularity = 106;  // cuMemGetAllocationGranularity
    constexpr int mem_retain_allocation_handle = 107;  // cuMemRetainAllocationHandle
    constexpr int module_load = 108;  // cuModuleLoad
    constexpr int module_load_data = 109;  // cuModuleLoadData
    constexpr int module_load_data_ex = 110;  // cuModuleLoadDataEx
    constexpr int module_load_fat_binary = 111;  // cuModuleLoadFatBinary
    constexpr int module_unload = 112;  // cuModuleUnload
    constexpr int module_get_function = 113;  // cuModuleGetFunction
    constexpr int module_get_global = 114;  // cuModuleGetGlobal
    constexpr int module_get_global_v2 = 115;  // cuModuleGetGlobal_v2
    constexpr int module_get_tex_ref = 116;  // cuModuleGetTexRef
    constexpr int module_get_surf_ref = 117;  // cuModuleGetSurfRef
    constexpr int launch_kernel = 118;  // cuLaunchKernel
    constexpr int launch_cooperative_kernel = 119;  // cuLaunchCooperativeKernel
    constexpr int launch_host_func = 120;  // cuLaunchHostFunc
    constexpr int get_proc_address = 121;  // cuGetProcAddress
    constexpr int get_proc_address_v2 = 122;  // cuGetProcAddress_v2
    constexpr int stream_create = 123;  // cuStreamCreate
    constexpr int stream_create_with_priority = 124;  // cuStreamCreateWithPriority
    constexpr int stream_destroy = 125;  // cuStreamDestroy
    constexpr int stream_destroy_v2 = 126;  // cuStreamDestroy_v2
    constexpr int stream_synchronize = 127;  // cuStreamSynchronize
    constexpr int stream_get_priority = 128;  // cuStreamGetPriority
    constexpr int stream_get_flags = 129;  // cuStreamGetFlags
    constexpr int stream_get_ctx = 130;  // cuStreamGetCtx
    constexpr int stream_wait_event = 131;  // cuStreamWaitEvent
    constexpr int stream_wait_event_ptsz = 132;  // cuStreamWaitEvent_ptsz
    constexpr int stream_add_callback = 133;  // cuStreamAddCallback
    constexpr int stream_add_callback_ptsz = 134;  // cuStreamAddCallback_ptsz
    constexpr int stream_begin_capture = 135;  // cuStreamBeginCapture
    constexpr int stream_begin_capture_ptsz = 136;  // cuStreamBeginCapture_ptsz
    constexpr int stream_end_capture = 137;  // cuStreamEndCapture
    constexpr int stream_end_capture_ptsz = 138;  // cuStreamEndCapture_ptsz
    constexpr int stream_is_capturing = 139;  // cuStreamIsCapturing
    constexpr int stream_attach_mem_async = 140;  // cuStreamAttachMemAsync
    constexpr int stream_attach_mem_async_ptsz = 141;  // cuStreamAttachMemAsync_ptsz
    constexpr int stream_query = 142;  // cuStreamQuery
    constexpr int stream_query_ptsz = 143;  // cuStreamQuery_ptsz
    constexpr int event_create = 144;  // cuEventCreate
    constexpr int event_record = 145;  // cuEventRecord
    constexpr int event_record_ptsz = 146;  // cuEventRecord_ptsz
    constexpr int event_record_with_flags = 147;  // cuEventRecordWithFlags
    constexpr int event_record_with_flags_ptsz = 148;  // cuEventRecordWithFlags_ptsz
    constexpr int event_destroy = 149;  // cuEventDestroy
    constexpr int event_destroy_v2 = 150;  // cuEventDestroy_v2
    constexpr int event_synchronize = 151;  // cuEventSynchronize
    constexpr int event_elapsed_time = 152;  // cuEventElapsedTime
    constexpr int event_query = 153;  // cuEventQuery
    constexpr int occupancy_max_active_blocks_per_multiprocessor = 154;  // cuOccupancyMaxActiveBlocksPerMultiprocessor
    constexpr int occupancy_max_active_blocks_per_multiprocessor_with_flags = 155;  // cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
    constexpr int occupancy_max_potential_block_size = 156;  // cuOccupancyMaxPotentialBlockSize
    constexpr int occupancy_max_potential_block_size_with_flags = 157;  // cuOccupancyMaxPotentialBlockSizeWithFlags
    constexpr int occupancy_available_dynamic_s_mem_per_block = 158;  // cuOccupancyAvailableDynamicSMemPerBlock
    constexpr int tex_ref_set_array = 159;  // cuTexRefSetArray
    constexpr int tex_ref_set_address = 160;  // cuTexRefSetAddress
    constexpr int tex_ref_set_address_v2 = 161;  // cuTexRefSetAddress_v2
    constexpr int tex_ref_set_format = 162;  // cuTexRefSetFormat
    constexpr int tex_ref_set_address_mode = 163;  // cuTexRefSetAddressMode
    constexpr int tex_ref_set_filter_mode = 164;  // cuTexRefSetFilterMode
    constexpr int tex_ref_set_mipmap_filter_mode = 165;  // cuTexRefSetMipmapFilterMode
    constexpr int tex_ref_set_mipmap_level_bias = 166;  // cuTexRefSetMipmapLevelBias
    constexpr int tex_ref_set_mipmap_level_clamp = 167;  // cuTexRefSetMipmapLevelClamp
    constexpr int tex_ref_set_max_anisotropy = 168;  // cuTexRefSetMaxAnisotropy
    constexpr int tex_ref_set_border_color = 169;  // cuTexRefSetBorderColor
    constexpr int tex_ref_set_flags = 170;  // cuTexRefSetFlags
    constexpr int tex_ref_get_array = 171;  // cuTexRefGetArray
    constexpr int tex_ref_get_address = 172;  // cuTexRefGetAddress
    constexpr int tex_ref_get_address_v2 = 173;  // cuTexRefGetAddress_v2
    constexpr int tex_ref_get_format = 174;  // cuTexRefGetFormat
    constexpr int tex_ref_get_address_mode = 175;  // cuTexRefGetAddressMode
    constexpr int tex_ref_get_filter_mode = 176;  // cuTexRefGetFilterMode
    constexpr int tex_ref_get_mipmap_filter_mode = 177;  // cuTexRefGetMipmapFilterMode
    constexpr int tex_ref_get_mipmap_level_bias = 178;  // cuTexRefGetMipmapLevelBias
    constexpr int tex_ref_get_mipmap_level_clamp = 179;  // cuTexRefGetMipmapLevelClamp
    constexpr int tex_ref_get_max_anisotropy = 180;  // cuTexRefGetMaxAnisotropy
    constexpr int tex_ref_get_border_color = 181;  // cuTexRefGetBorderColor
    constexpr int tex_ref_get_flags = 182;  // cuTexRefGetFlags
    constexpr int surf_ref_set_array = 183;  // cuSurfRefSetArray
    constexpr int surf_ref_get_array = 184;  // cuSurfRefGetArray
    constexpr int array_destroy = 185;  // cuArrayDestroy
    constexpr int mipmapped_array_get_level = 186;  // cuMipmappedArrayGetLevel
    constexpr int mipmapped_array_destroy = 187;  // cuMipmappedArrayDestroy
    constexpr int pointer_get_attribute = 188;  // cuPointerGetAttribute
    constexpr int pointer_set_attribute = 189;  // cuPointerSetAttribute
    constexpr int device_can_access_peer = 190;  // cuDeviceCanAccessPeer
    constexpr int ctx_enable_peer_access = 191;  // cuCtxEnablePeerAccess
    constexpr int ctx_disable_peer_access = 192;  // cuCtxDisablePeerAccess
    constexpr int graph_create = 193;  // cuGraphCreate
    constexpr int graph_destroy = 194;  // cuGraphDestroy
    constexpr int graph_add_memcpy_node1_d = 195;  // cuGraphAddMemcpyNode1D
    constexpr int graph_add_empty_node = 196;  // cuGraphAddEmptyNode
    constexpr int graph_add_event_record_node = 197;  // cuGraphAddEventRecordNode
    constexpr int graph_add_event_wait_node = 198;  // cuGraphAddEventWaitNode
    constexpr int graph_add_child_graph_node = 199;  // cuGraphAddChildGraphNode
    constexpr int graph_node_get_type = 200;  // cuGraphNodeGetType
    constexpr int graph_destroy_node = 201;  // cuGraphDestroyNode
    constexpr int graph_instantiate_with_flags = 202;  // cuGraphInstantiateWithFlags
    constexpr int graph_launch = 203;  // cuGraphLaunch
    constexpr int graph_launch_ptsz = 261;  // cuGraphLaunch_ptsz
    constexpr int graph_exec_destroy = 205;  // cuGraphExecDestroy
    constexpr int graph_clone = 206;  // cuGraphClone
    constexpr int graph_node_find_in_clone = 207;  // cuGraphNodeFindInClone
    constexpr int graph_exec_event_record_node_set_event = 208;  // cuGraphExecEventRecordNodeSetEvent
    constexpr int graph_exec_event_wait_node_set_event = 209;  // cuGraphExecEventWaitNodeSetEvent
    constexpr int graph_event_record_node_get_event = 210;  // cuGraphEventRecordNodeGetEvent
    constexpr int graph_event_wait_node_get_event = 211;  // cuGraphEventWaitNodeGetEvent
    constexpr int graph_upload = 212;  // cuGraphUpload
    constexpr int stream_write_value32 = 213;  // cuStreamWriteValue32
    constexpr int stream_write_value32_ptsz = 214;  // cuStreamWriteValue32_ptsz
    constexpr int stream_write_value64 = 215;  // cuStreamWriteValue64
    constexpr int stream_write_value64_ptsz = 216;  // cuStreamWriteValue64_ptsz
    constexpr int stream_read_value32 = 217;  // cuStreamReadValue32
    constexpr int stream_read_value32_ptsz = 218;  // cuStreamReadValue32_ptsz
    constexpr int stream_read_value64 = 219;  // cuStreamReadValue64
    constexpr int stream_read_value64_ptsz = 220;  // cuStreamReadValue64_ptsz
    constexpr int profiler_initialize = 221;  // cuProfilerInitialize
    constexpr int profiler_start = 222;  // cuProfilerStart
    constexpr int profiler_stop = 223;  // cuProfilerStop
    constexpr int mem_advise = 224;  // cuMemAdvise
    constexpr int mem_advise_v2 = 225;  // cuMemAdvise_v2
    constexpr int mem_prefetch_async = 226;  // cuMemPrefetchAsync
    constexpr int mem_prefetch_async_v2 = 227;  // cuMemPrefetchAsync_v2
    constexpr int mem_range_get_attribute = 228;  // cuMemRangeGetAttribute
    constexpr int func_get_attribute = 229;  // cuFuncGetAttribute
    constexpr int func_set_attribute = 230;  // cuFuncSetAttribute
    constexpr int func_set_cache_config = 231;  // cuFuncSetCacheConfig
    constexpr int func_set_shared_mem_config = 232;  // cuFuncSetSharedMemConfig
    constexpr int func_get_module = 233;  // cuFuncGetModule
    constexpr int func_get_name = 234;  // cuFuncGetName
    constexpr int func_is_loaded = 235;  // cuFuncIsLoaded
    constexpr int func_load = 236;  // cuFuncLoad
    constexpr int library_load_data = 237;  // cuLibraryLoadData
    constexpr int library_load_from_file = 238;  // cuLibraryLoadFromFile
    constexpr int library_unload = 239;  // cuLibraryUnload
    constexpr int library_get_kernel = 240;  // cuLibraryGetKernel
    constexpr int library_get_module = 241;  // cuLibraryGetModule
    constexpr int kernel_get_function = 242;  // cuKernelGetFunction
    constexpr int kernel_get_attribute = 243;  // cuKernelGetAttribute
    constexpr int kernel_set_attribute = 244;  // cuKernelSetAttribute
    constexpr int kernel_set_cache_config = 245;  // cuKernelSetCacheConfig
    constexpr int library_get_global = 246;  // cuLibraryGetGlobal
    constexpr int library_get_managed = 247;  // cuLibraryGetManaged
    constexpr int library_get_unified_function = 248;  // cuLibraryGetUnifiedFunction
    constexpr int memcpy_ptds = 249;  // cuMemcpy_ptds
    constexpr int memcpy_async_ptds = 250;  // cuMemcpyAsync_ptds
    constexpr int memcpy_hto_d_ptds = 251;  // cuMemcpyHtoD_ptds
    constexpr int memcpy_dto_h_ptds = 252;  // cuMemcpyDtoH_ptds
    constexpr int memcpy_hto_d_async_ptsz = 253;  // cuMemcpyHtoDAsync_ptsz
    constexpr int memcpy_dto_h_async_ptsz = 254;  // cuMemcpyDtoHAsync_ptsz
    constexpr int memset_d8_ptds = 255;  // cuMemsetD8_ptds
    constexpr int memset_d32_ptds = 256;  // cuMemsetD32_ptds
    constexpr int memset_d8_async_ptsz = 257;  // cuMemsetD8Async_ptsz
    constexpr int memset_d32_async_ptsz = 258;  // cuMemsetD32Async_ptsz
    constexpr int stream_synchronize_ptsz = 259;  // cuStreamSynchronize_ptsz
    constexpr int ctx_synchronize_ptds = 260;  // cuCtxSynchronize_ptds
    constexpr int graph_launch_ptsz = 261;  // cuGraphLaunch_ptsz
    constexpr int mem_alloc_from_pool_async = 262;  // cuMemAllocFromPoolAsync
    constexpr int mem_alloc_from_pool_async_ptsz = 263;  // cuMemAllocFromPoolAsync_ptsz
    constexpr int mem_alloc_async = 264;  // cuMemAllocAsync
    constexpr int mem_free_async = 265;  // cuMemFreeAsync
    constexpr int mem_pool_trim_to = 266;  // cuMemPoolTrimTo
    constexpr int mem_pool_set_attribute = 267;  // cuMemPoolSetAttribute
    constexpr int mem_pool_get_attribute = 268;  // cuMemPoolGetAttribute
    constexpr int mem_pool_create = 269;  // cuMemPoolCreate
    constexpr int mem_pool_destroy = 270;  // cuMemPoolDestroy
}

} // namespace cuda_gen